/**
 * CurateExecutor regression tests
 *
 * 1. Variable naming: UUID hyphens in sandbox variable names cause
 *    ReferenceError when LLM writes code using underscores.
 *
 * 2. Session-leak fix: createTaskSession must not be called before
 *    processFileReferences, so a preprocessing failure cannot leak sessions.
 */

import {expect} from 'chai'
import {restore, stub} from 'sinon'

import type {ICipherAgent} from '../../../../src/agent/core/interfaces/i-cipher-agent.js'

import {LocalSandbox} from '../../../../src/agent/infra/sandbox/local-sandbox.js'
import {FileValidationError} from '../../../../src/server/core/domain/errors/task-error.js'
import {CurateExecutor} from '../../../../src/server/infra/executor/curate-executor.js'

describe('CurateExecutor (regression)', () => {
  afterEach(() => {
    restore()
  })

  describe('sandbox variable naming', () => {
    // Typical UUID taskId with hyphens (as generated by crypto.randomUUID())
    const taskId = '8cd8e2d8-a7fc-4371-89ca-59460687c12d'
    // What the LLM would write in code-exec (hyphens → underscores, valid JS identifier)
    const llmGeneratedVarName = '__curate_meta_8cd8e2d8_a7fc_4371_89ca_59460687c12d'

    describe('bug: hyphenated taskId causes variable name mismatch', () => {
      it('should fail with ReferenceError when variable stored with hyphens but accessed with underscores', async () => {
        const sandbox = new LocalSandbox()

        // Old (buggy) behavior: store variable using raw taskId containing hyphens
        const buggyMetaVar = `__curate_meta_${taskId}` // "..._8cd8e2d8-a7fc-..."
        sandbox.updateContext({[buggyMetaVar]: {charCount: 100, lineCount: 5}})

        // LLM writes underscores in code (hyphens are not valid JS identifier chars)
        const result = await sandbox.execute(llmGeneratedVarName)

        // Variable is in sandbox as hyphen-version, but LLM looks up underscore-version → not found
        expect(result.stderr).to.include('ReferenceError')
        expect(result.stderr).to.include(llmGeneratedVarName)
      })
    })

    describe('fix: taskIdSafe with underscores eliminates mismatch', () => {
      it('should succeed when variable stored with underscores matching LLM output', async () => {
        const sandbox = new LocalSandbox()

        // Fixed behavior: replace hyphens before naming sandbox variables
        const taskIdSafe = taskId.replaceAll('-', '_')
        const fixedMetaVar = `__curate_meta_${taskIdSafe}` // all underscores
        sandbox.updateContext({[fixedMetaVar]: {charCount: 100, lineCount: 5}})

        // LLM writes underscores → now matches sandbox variable
        const result = await sandbox.execute(`${llmGeneratedVarName}.charCount`)

        expect(result.stderr).to.equal('')
        expect(result.returnValue).to.equal(100)
      })

      it('should correctly transform all UUID segments (4 hyphens replaced)', () => {
        const taskIdSafe = taskId.replaceAll('-', '_')

        expect(taskIdSafe).to.not.include('-')
        expect(taskIdSafe).to.equal('8cd8e2d8_a7fc_4371_89ca_59460687c12d')

        const metaVar = `__curate_meta_${taskIdSafe}`
        expect(metaVar).to.equal(llmGeneratedVarName)
      })
    })
  })

  describe('session-leak fix', () => {
    it('should not call createTaskSession when processFileReferences throws', async () => {
      const createTaskSession = stub().resolves('session-id')
      const deleteTaskSession = stub().resolves()

      const agent = {
        cancel: stub().resolves(false),
        createTaskSession,
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession,
        execute: stub().resolves(''),
        executeOnSession: stub().resolves(''),
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      // Pass non-existent file paths to trigger FileValidationError in processFileReferences
      const executor = new CurateExecutor()
      const options = {
        content: 'test content',
        files: ['/nonexistent/path/to/file.txt', '/another/invalid/file.md'],
        taskId: 'task-123',
      }

      try {
        await executor.executeWithAgent(agent, options)
        expect.fail('Should have thrown FileValidationError')
      } catch (error) {
        expect(error).to.be.instanceOf(FileValidationError)
      }

      // Key assertion: createTaskSession was NEVER called because
      // processFileReferences runs BEFORE createTaskSession in the restructured code.
      // Previously, createTaskSession ran first and the session would leak on throw.
      expect(createTaskSession.called).to.be.false
      expect(deleteTaskSession.called).to.be.false
    })
  })

  describe('background queue drain', () => {
    it('waits for background work before returning curate results', async () => {
      const createTaskSession = stub().resolves('session-id')
      const deleteTaskSession = stub().resolves()
      const drainBackgroundWork = stub().resolves()
      const executeOnSession = stub().resolves('curated')

      const agent = {
        cancel: stub().resolves(false),
        createTaskSession,
        deleteSandboxVariable: stub(),
        deleteSandboxVariableOnSession: stub(),
        deleteSession: stub().resolves(true),
        deleteTaskSession,
        drainBackgroundWork,
        execute: stub().resolves(''),
        executeOnSession,
        generate: stub().resolves({content: '', toolCalls: [], usage: {inputTokens: 0, outputTokens: 0}}),
        getSessionMetadata: stub().resolves(),
        getState: stub().returns({currentIteration: 0, executionHistory: [], executionState: 'idle', toolCallsExecuted: 0}),
        listPersistedSessions: stub().resolves([]),
        reset: stub(),
        setSandboxVariable: stub(),
        setSandboxVariableOnSession: stub(),
        start: stub().resolves(),
        stream: stub().resolves({[Symbol.asyncIterator]: () => ({next: () => Promise.resolve({done: true, value: undefined})})}),
      } as unknown as ICipherAgent

      const executor = new CurateExecutor()
      const response = await executor.executeWithAgent(agent, {
        clientCwd: '/workspace',
        content: 'capture auth knowledge',
        taskId: 'task-123',
      })

      expect(response).to.equal('curated')
      expect(drainBackgroundWork.calledOnce).to.be.true
      expect(deleteTaskSession.calledOnceWithExactly('session-id')).to.be.true
      expect(drainBackgroundWork.calledBefore(deleteTaskSession)).to.be.true
    })
  })
})
