/**
 * QueryExecutor variable naming regression test
 *
 * Reproduces and verifies the fix for: UUID hyphens in sandbox variable names cause
 * ReferenceError when LLM writes code using underscores (hyphens are invalid in JS identifiers).
 *
 * Root cause: query-executor used raw taskId (e.g. "8cd8e2d8-a7fc-...") to name sandbox
 * variables (__query_results_*, __query_meta_*), but the LLM sanitizes hyphens to underscores
 * when writing code-exec calls, causing a variable name mismatch → ReferenceError.
 *
 * Fix: taskIdSafe = taskId.replaceAll('-', '_') ensures sandbox variable names match
 * what the LLM would generate.
 */

import {expect} from 'chai'
import {restore, stub} from 'sinon'

import type {ICipherAgent} from '../../../../src/agent/core/interfaces/i-cipher-agent.js'
import type {IFileSystem} from '../../../../src/agent/core/interfaces/i-file-system.js'
import type {SearchKnowledgeResult} from '../../../../src/agent/infra/sandbox/tools-sdk.js'
import type {QueryHarnessService} from '../../../../src/server/infra/harness/query/query-harness-service.js'

import {LocalSandbox} from '../../../../src/agent/infra/sandbox/local-sandbox.js'
import {QueryExecutor} from '../../../../src/server/infra/executor/query-executor.js'

function makeSearchResult(
  results: SearchKnowledgeResult['results'],
): SearchKnowledgeResult {
  return {
    message: 'ok',
    results,
    totalFound: results.length,
  }
}

function makeResult(overrides: Partial<SearchKnowledgeResult['results'][number]> = {}): SearchKnowledgeResult['results'][number] {
  return {
    excerpt: 'excerpt',
    path: 'auth/login.md',
    score: 0.5,
    symbolPath: 'auth/login/handler',
    title: 'Auth Login',
    ...overrides,
  }
}

function createMockFileSystem() {
  const fileSystem = {
    editFile: stub(),
    globFiles: stub().resolves({
      files: [{modified: new Date(1), path: 'auth/login.md'}],
    }),
    initialize: stub().resolves(),
    listDirectory: stub(),
    readFile: stub().resolves({content: '# Auth Login\nDetails'}),
    searchContent: stub(),
    writeFile: stub(),
  }

  return fileSystem as IFileSystem & typeof fileSystem
}

function createMockAgent() {
  const agent = {
    cancel: stub().resolves(false),
    createTaskSession: stub().resolves('task-session'),
    deleteSandboxVariable: stub(),
    deleteSandboxVariableOnSession: stub(),
    deleteSession: stub().resolves(false),
    deleteTaskSession: stub().resolves(),
    execute: stub(),
    executeOnSession: stub().resolves('LLM answer'),
    generate: stub(),
    getSessionMetadata: stub().resolves(),
    getState: stub(),
    listPersistedSessions: stub().resolves([]),
    reset: stub(),
    setSandboxVariable: stub(),
    setSandboxVariableOnSession: stub(),
    start: stub().resolves(),
    stream: stub(),
  }

  return {
    agent: agent as unknown as ICipherAgent,
    stubs: agent,
  }
}

function createQueryHarnessStub() {
  const harness = {
    adjustBoosts: stub().callsFake(async (results) => ({nodeId: 'boost-node', results})),
    decomposeQuery: stub().resolves({
      decomposed: {domainHints: [], expandedTerms: [], originalQuery: ''},
      nodeId: 'decompose-node',
    }),
    recordOutcome: stub().resolves(),
    refineIfNeeded: stub().resolves(),
    rerankResults: stub().callsFake(async (results) => ({nodeId: 'rerank-node', results})),
  }

  return harness as QueryHarnessService & typeof harness
}

describe('QueryExecutor', () => {
  afterEach(() => {
    restore()
  })

  describe('sandbox variable naming (regression)', () => {
    // Typical UUID taskId with hyphens (as generated by crypto.randomUUID())
    const taskId = '8cd8e2d8-a7fc-4371-89ca-59460687c12d'
    // What the LLM would write in code-exec (hyphens → underscores, valid JS identifier)
    const llmGeneratedResultsVar = '__query_results_8cd8e2d8_a7fc_4371_89ca_59460687c12d'
    const llmGeneratedMetaVar = '__query_meta_8cd8e2d8_a7fc_4371_89ca_59460687c12d'

    describe('bug: hyphenated taskId causes variable name mismatch', () => {
      it('should fail with ReferenceError when __query_results_* stored with hyphens', async () => {
        const sandbox = new LocalSandbox()

        const buggyResultsVar = `__query_results_${taskId}`
        sandbox.updateContext({[buggyResultsVar]: [{path: '/a.md', score: 0.9}]})

        const result = await sandbox.execute(llmGeneratedResultsVar)

        expect(result.stderr).to.include('ReferenceError')
        expect(result.stderr).to.include(llmGeneratedResultsVar)
      })

      it('should fail with ReferenceError when __query_meta_* stored with hyphens', async () => {
        const sandbox = new LocalSandbox()

        const buggyMetaVar = `__query_meta_${taskId}`
        sandbox.updateContext({[buggyMetaVar]: {resultCount: 3, topScore: 0.9, totalFound: 10}})

        const result = await sandbox.execute(`${llmGeneratedMetaVar}.resultCount`)

        expect(result.stderr).to.include('ReferenceError')
      })
    })

    describe('fix: taskIdSafe with underscores eliminates mismatch', () => {
      it('should succeed when __query_results_* stored with underscores matching LLM output', async () => {
        const sandbox = new LocalSandbox()

        const taskIdSafe = taskId.replaceAll('-', '_')
        const fixedResultsVar = `__query_results_${taskIdSafe}`
        sandbox.updateContext({[fixedResultsVar]: [{path: '/a.md', score: 0.9}]})

        const result = await sandbox.execute(`${llmGeneratedResultsVar}[0].score`)

        expect(result.stderr).to.equal('')
        expect(result.returnValue).to.equal(0.9)
      })

      it('should succeed when __query_meta_* stored with underscores matching LLM output', async () => {
        const sandbox = new LocalSandbox()

        const taskIdSafe = taskId.replaceAll('-', '_')
        const fixedMetaVar = `__query_meta_${taskIdSafe}`
        sandbox.updateContext({[fixedMetaVar]: {resultCount: 3, topScore: 0.9, totalFound: 10}})

        const result = await sandbox.execute(`${llmGeneratedMetaVar}.resultCount`)

        expect(result.stderr).to.equal('')
        expect(result.returnValue).to.equal(3)
      })

      it('should correctly transform all UUID segments (4 hyphens replaced)', () => {
        const taskIdSafe = taskId.replaceAll('-', '_')

        expect(taskIdSafe).to.not.include('-')
        expect(taskIdSafe).to.equal('8cd8e2d8_a7fc_4371_89ca_59460687c12d')

        expect(`__query_results_${taskIdSafe}`).to.equal(llmGeneratedResultsVar)
        expect(`__query_meta_${taskIdSafe}`).to.equal(llmGeneratedMetaVar)
      })
    })
  })

  describe('with QueryHarnessService', () => {

  it('skips decomposition and search on exact cache hits', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([makeResult({score: 0.95})]))}
    const queryHarness = createQueryHarnessStub()
    const {agent, stubs} = createMockAgent()
    const executor = new QueryExecutor({
      enableCache: true,
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const first = await executor.executeWithAgent(agent, {query: 'what is auth', taskId: 'task-1'})
    const second = await executor.executeWithAgent(agent, {query: 'what is auth', taskId: 'task-2'})

    expect(second).to.equal(first)
    expect(queryHarness.decomposeQuery.callCount).to.equal(1)
    expect(searchService.search.callCount).to.equal(1)
    expect(stubs.createTaskSession.called).to.equal(false)
  })

  it('expands the effective query, applies boost/rerank, and records a Tier 4 outcome', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([makeResult({score: 0.5})]))}
    const queryHarness = createQueryHarnessStub()
    queryHarness.decomposeQuery.resolves({
      decomposed: {domainHints: ['auth'], expandedTerms: ['jwt', 'token'], originalQuery: 'how auth works'},
      nodeId: 'decompose-node',
    })

    const {agent} = createMockAgent()
    const executor = new QueryExecutor({
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const result = await executor.executeWithAgent(agent, {query: 'how auth works', taskId: 'task-1'})

    expect(result).to.equal('LLM answer\n\n---\nSource: ByteRover Knowledge Base')
    expect(searchService.search.firstCall.args).to.deep.equal(['how auth works jwt token', {limit: 5}])
    expect(queryHarness.adjustBoosts.calledOnce).to.equal(true)
    expect(queryHarness.adjustBoosts.firstCall.args[1]).to.equal('how auth works')
    expect(queryHarness.adjustBoosts.firstCall.args[2]).to.deep.equal(['auth'])
    expect(queryHarness.rerankResults.calledOnce).to.equal(true)
    expect(queryHarness.recordOutcome.calledOnce).to.equal(true)
    expect(queryHarness.recordOutcome.firstCall.args[0]).to.deep.equal({
      boost: 'boost-node',
      decompose: 'decompose-node',
      rerank: 'rerank-node',
    })
    expect(queryHarness.recordOutcome.firstCall.args[1]).to.deep.include({
      directHit: false,
      ood: false,
      prefetched: false,
      supplemented: false,
      tier: 4,
    })
  })

  it('records a Tier 2 direct-hit outcome', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([makeResult({score: 0.95})]))}
    const queryHarness = createQueryHarnessStub()
    const {agent, stubs} = createMockAgent()
    const executor = new QueryExecutor({
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const result = await executor.executeWithAgent(agent, {query: 'what is auth', taskId: 'task-1'})

    expect(result).to.include('Source: ByteRover Knowledge Base')
    expect(queryHarness.recordOutcome.calledOnce).to.equal(true)
    expect(queryHarness.recordOutcome.firstCall.args[1]).to.deep.include({
      directHit: true,
      ood: false,
      prefetched: false,
      supplemented: false,
      tier: 2,
    })
    expect(stubs.executeOnSession.called).to.equal(false)
  })

  it('records an OOD outcome when search returns no results', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([]))}
    const queryHarness = createQueryHarnessStub()
    const {agent, stubs} = createMockAgent()
    const executor = new QueryExecutor({
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const result = await executor.executeWithAgent(agent, {query: 'unknown topic', taskId: 'task-1'})

    expect(result).to.include('No matching knowledge found')
    expect(queryHarness.recordOutcome.calledOnce).to.equal(true)
    expect(queryHarness.recordOutcome.firstCall.args[1]).to.deep.include({
      directHit: false,
      ood: true,
      prefetched: false,
      supplemented: false,
      tier: 0,
    })
    expect(stubs.executeOnSession.called).to.equal(false)
  })

  it('records a Tier 3 outcome when prefetched context is used', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([makeResult({score: 0.8})]))}
    const queryHarness = createQueryHarnessStub()
    const {agent} = createMockAgent()
    const executor = new QueryExecutor({
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const result = await executor.executeWithAgent(agent, {query: 'auth overview', taskId: 'task-1'})

    expect(result).to.equal('LLM answer\n\n---\nSource: ByteRover Knowledge Base')
    expect(queryHarness.recordOutcome.calledOnce).to.equal(true)
    expect(queryHarness.recordOutcome.firstCall.args[1]).to.deep.include({
      directHit: false,
      ood: false,
      prefetched: true,
      supplemented: false,
      tier: 3,
    })
  })

  it('fails open when decomposition throws and falls back to the original query', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([makeResult({score: 0.5})]))}
    const queryHarness = createQueryHarnessStub()
    queryHarness.decomposeQuery.rejects(new Error('boom'))
    const {agent} = createMockAgent()
    const executor = new QueryExecutor({
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const result = await executor.executeWithAgent(agent, {query: 'auth query', taskId: 'task-1'})

    expect(result).to.equal('LLM answer\n\n---\nSource: ByteRover Knowledge Base')
    expect(searchService.search.firstCall.args).to.deep.equal(['auth query', {limit: 5}])
  })

  it('fails open when reranking throws and still returns an answer', async () => {
    const fileSystem = createMockFileSystem()
    const searchService = {search: stub().resolves(makeSearchResult([makeResult({score: 0.5})]))}
    const queryHarness = createQueryHarnessStub()
    queryHarness.rerankResults.rejects(new Error('boom'))
    const {agent} = createMockAgent()
    const executor = new QueryExecutor({
      fileSystem,
      queryHarnessService: queryHarness,
      searchService,
    })

    const result = await executor.executeWithAgent(agent, {query: 'auth query', taskId: 'task-1'})

    expect(result).to.equal('LLM answer\n\n---\nSource: ByteRover Knowledge Base')
    expect(queryHarness.recordOutcome.calledOnce).to.equal(true)
    expect(queryHarness.recordOutcome.firstCall.args[0]).to.deep.equal({
      boost: 'boost-node',
      decompose: 'decompose-node',
    })
  })
  })
})
