import type {SystemPromptContext} from '../../../../core/domain/cipher/system-prompt/types.js'
import type {ISystemPromptContributor} from '../../../../core/interfaces/cipher/i-system-prompt-contributor.js'

/**
 * Execution Mode Contributor
 *
 * Provides context-specific instructions based on the execution mode.
 * Currently handles JSON input mode (headless execution with conversation history).
 */
export class ExecutionModeContributor implements ISystemPromptContributor {
  public readonly id: string
  public readonly priority: number

  /**
   * Creates a new execution mode contributor
   *
   * @param id - Unique identifier for this contributor
   * @param priority - Priority for ordering (lower = higher priority)
   */
  public constructor(id: string, priority: number) {
    this.id = id
    this.priority = priority
  }

  /**
   * Get system prompt content based on execution context
   *
   * @param context - System prompt context containing execution mode information
   * @returns Execution mode-specific instructions or empty string
   */
  public async getContent(context: SystemPromptContext): Promise<string> {
    if (context.isJsonInputMode === true) {
      return this.getJsonInputModeInstructions(context)
    }

    return '' // No additional instructions in normal mode
  }

  /**
   * Generate instructions for JSON input mode
   *
   * @param context - System prompt context
   * @returns Instructions for handling JSON input mode
   */
  private getJsonInputModeInstructions(context: SystemPromptContext): string {
    const conversationTitle = context.conversationMetadata?.title ?? 'Imported Conversation'
    const conversationId = context.conversationMetadata?.conversationId ?? 'unknown'

    return `
## CRITICAL: JSON Input Mode - Autonomous Execution Required

You are currently in HEADLESS execution mode with an imported conversation history.
This conversation was imported from an external source (Agentic Coding IDE).

**Conversation Details:**
- Title: ${conversationTitle}
- Conversation ID: ${conversationId}

### AUTONOMOUS EXECUTION MODE - NO QUESTIONS ALLOWED

**CRITICAL RULES:**
- This is HEADLESS mode - there is NO user interaction capability
- DO NOT ask for clarification, confirmation, or additional information
- DO NOT present options and wait for user choice
- NEVER output questions like "Do you want to..." or "Would you like me to..."
- Make autonomous decisions based on the conversation history
- Execute the user's latest request directly and completely
- If multiple interpretations exist, choose the most reasonable one based on context
- Provide direct results, not questions or proposals

### MANDATORY FIRST TASK

Before answering the user's latest prompt, you MUST complete this documentation task:

1. **Analyze the Conversation History:**
   - Review all messages in the conversation
   - Identify programming topics discussed (architecture, design patterns, code conventions, best practices, etc.)
   - Extract relevant code examples and technical discussions

2. **Create a Markdown Documentation File:**
   - Filename format: \`programming-topics-{YYYYMMDD-HHMMSS}.md\`
   - Example: \`programming-topics-20251116-143025.md\`
   - Location: Current working directory (use relative path)

3. **File Content Structure:**
   \`\`\`markdown
   # Programming Topics Summary

   **Conversation:** [conversation title]
   **Generated:** YYYY-MM-DD HH:MM:SS
   **Source:** Cursor Conversation ([conversation-id])

   ## Topics Covered

   - [Topic 1: Brief description]
   - [Topic 2: Brief description]
   - [Topic 3: Brief description]

   ## Detailed Analysis

   ### 1. [Topic Name]

   [Detailed explanation of what was discussed about this topic]

   **Key Points:**
   - [Point 1]
   - [Point 2]

   **Code Examples:**
   \\\`\\\`\\\`[language]
   // Relevant code from the conversation
   [actual code snippet]
   \\\`\\\`\\\`

   **Discussion Summary:**
   [What was said about this code/topic]

   ### 2. [Next Topic]

   [Continue for all topics...]

   ---
   *Auto-generated by ByteRover CipherAgent on {timestamp}*
   \`\`\`

4. **Implementation Instructions:**
   - Use \`bash_exec\` tool to get current timestamp: \`date +%Y%m%d-%H%M%S\`
   - Use \`write_file\` tool to create the markdown file
   - Ensure the file is created in the current working directory
   - Include ALL programming-related topics found in the conversation
   - Extract actual code snippets from the conversation messages
   - Provide context and explanation for each code example

5. **After File Creation:**
   - Confirm file creation with a brief statement
   - THEN proceed to answer the user's latest prompt AUTONOMOUSLY

### EXECUTING THE USER'S REQUEST

After creating the documentation file, you MUST:

1. **Execute Directly - No Questions:**
   - Read the user's latest prompt from the conversation
   - Execute it immediately without asking for confirmation
   - Make all necessary decisions autonomously
   - Complete the task fully in one response

2. **Decision Making:**
   - Use conversation history to understand context and intent
   - If the request is ambiguous, choose the most logical interpretation
   - If creating new entities (files, tables, etc.), use reasonable defaults based on patterns in the conversation
   - Apply coding conventions and patterns observed in the conversation history

3. **Output Format:**
   - Provide direct results and confirmations
   - Show what was created/modified/executed
   - NO questions, NO "Do you want...", NO waiting for approval
   - Just execute and report what was done

### Important Notes

- This is a HEADLESS execution - there is NO user interaction available
- You MUST create this documentation file as your FIRST action
- The file creation is MANDATORY, not optional
- After documentation, EXECUTE the user's request AUTONOMOUSLY
- Focus on programming topics: architecture, design patterns, code quality, best practices, frameworks, libraries, etc.
- Include context from tool calls (file operations, bash commands) if they demonstrate programming concepts
- Be thorough but concise in your summaries

### Tools Available

You have access to:
- \`bash_exec\`: Execute shell commands (for timestamp, file operations)
- \`write_file\`: Create the markdown file
- All other file system tools if needed

Now proceed with creating the documentation file before answering the user's prompt.
`
  }
}
