/**
 * ByteRover CLI generated rule template tag.
 */
export const BRV_RULE_TAG = 'Generated by ByteRover CLI for'

/**
 * Boundary markers for managed ByteRover rule sections.
 * Used to identify and replace ByteRover-generated content in shared instruction files.
 */
export const BRV_RULE_MARKERS = {
  END: '<!-- END BYTEROVER RULES -->',
  START: '<!-- BEGIN BYTEROVER RULES -->',
} as const
