import {expect} from 'chai'

import {LegacyRuleDetector} from '../../../../../src/server/infra/connectors/rules/legacy-rule-detector.js'

describe('LegacyRuleDetector', () => {
  let detector: LegacyRuleDetector

  beforeEach(() => {
    detector = new LegacyRuleDetector()
  })

  describe('detectLegacyRules()', () => {
    describe('with no ByteRover rules', () => {
      it('should return empty arrays when file has no ByteRover content', () => {
        const content = [
          "# User's Custom Instructions",
          '',
          'This is my custom content for the agent.',
          'No ByteRover rules here.',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(0)
        expect(result.uncertainMatches).to.have.lengthOf(0)
      })

      it('should return empty arrays when file is empty', () => {
        const result = detector.detectLegacyRules('', 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(0)
        expect(result.uncertainMatches).to.have.lengthOf(0)
      })
    })

    describe('with reliable matches (workflow header)', () => {
      it('should detect single section with workflow header', () => {
        const content = [
          '# Workflow Instruction',
          '',
          'You are a coding agent.',
          'Use brv CLI.',
          '',
          '---',
          '[command reference content]',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.uncertainMatches).to.have.lengthOf(0)

        const match = result.reliableMatches[0]
        expect(match.startLine).to.equal(1)
        expect(match.endLine).to.equal(9)
        expect(match.content).to.include('# Workflow Instruction')
        expect(match.content).to.include('Generated by ByteRover CLI for Github Copilot')
      })

      it('should detect multiple duplicate sections', () => {
        const content = [
          '# User content',
          '',
          '# Workflow Instruction',
          'First section',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
          '',
          '# Workflow Instruction',
          'Second section',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
          '',
          '# Workflow Instruction',
          'Third section',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(3)
        expect(result.uncertainMatches).to.have.lengthOf(0)

        expect(result.reliableMatches[0].startLine).to.equal(3)
        expect(result.reliableMatches[1].startLine).to.equal(8)
        expect(result.reliableMatches[2].startLine).to.equal(13)
      })

      it('should preserve user content before and after ByteRover sections', () => {
        const content = [
          'My custom instructions here',
          '',
          '# Workflow Instruction',
          'ByteRover content',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
          '',
          'More custom instructions',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        const match = result.reliableMatches[0]
        expect(match.content).to.not.include('My custom instructions')
        expect(match.content).to.not.include('More custom instructions')
      })
    })

    describe('with separator fallback', () => {
      it('should detect section using separator when workflow header is missing', () => {
        const content = [
          'User content before',
          '',
          'Some content without header',
          '---',
          '[command reference]',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.uncertainMatches).to.have.lengthOf(0)

        const match = result.reliableMatches[0]
        // Should start after the first separator
        expect(match.content).to.include('[command reference]')
        expect(match.content).to.include('Generated by ByteRover CLI for Github Copilot')
      })

      it('should skip the separator immediately before footer', () => {
        const content = ['Content', '---', 'More content', '---', 'Generated by ByteRover CLI for Github Copilot'].join(
          '\n',
        )

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        // Should start after the first separator, not the one right before the footer
        const match = result.reliableMatches[0]
        expect(match.content).to.include('More content')
      })
    })

    describe('with uncertain matches', () => {
      it('should mark as uncertain when no workflow header or separator found', () => {
        const content = 'Generated by ByteRover CLI for Github Copilot'

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(0)
        expect(result.uncertainMatches).to.have.lengthOf(1)

        const match = result.uncertainMatches[0]
        expect(match.footerLine).to.equal(1)
        expect(match.reason).to.include('Could not reliably determine')
      })

      it('should handle mixed reliable and uncertain matches', () => {
        const content = [
          '# Workflow Instruction',
          'Reliable section',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
          '',
          'No clear start here',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.uncertainMatches).to.have.lengthOf(1)

        expect(result.reliableMatches[0].startLine).to.equal(1)
        expect(result.uncertainMatches[0].footerLine).to.equal(7)
      })
    })

    describe('with different agent names', () => {
      it('should only match the specified agent', () => {
        const content = [
          '# Workflow Instruction',
          'Content',
          '---',
          'Generated by ByteRover CLI for Claude Code',
          '',
          '# Workflow Instruction',
          'Content',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.reliableMatches[0].content).to.include('Generated by ByteRover CLI for Github Copilot')
        expect(result.reliableMatches[0].content).to.not.include('Generated by ByteRover CLI for Claude Code')
      })

      it('should not match partial agent names', () => {
        const content = [
          '# Workflow Instruction',
          'Content',
          '---',
          'Generated by ByteRover CLI for Github',
          '',
          '# Workflow Instruction',
          'Content',
          '---',
          'Generated by ByteRover CLI for Github Copilot Extended',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(0)
        expect(result.uncertainMatches).to.have.lengthOf(0)
      })
    })

    describe('edge cases', () => {
      it('should handle workflow header with exact spacing', () => {
        const invalidHeader = '#  Workflow Instruction' // Two spaces
        const validHeader = '# Workflow Instruction' // One space
        const content = [
          invalidHeader,
          'Should not match',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
          '',
          validHeader,
          'Should match',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.uncertainMatches).to.have.lengthOf(1)
        expect(result.reliableMatches[0].content).to.include('Should match')
      })

      it('should handle content with many separators', () => {
        const content = [
          '---',
          '---',
          '---',
          '# Workflow Instruction',
          'Content',
          '---',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.reliableMatches[0].startLine).to.equal(4)
      })

      it('should handle Windows line endings (CRLF)', () => {
        const content = '# Workflow Instruction\r\nContent\r\n---\r\nGenerated by ByteRover CLI for Github Copilot'

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
      })
    })

    describe('line number accuracy', () => {
      it('should report accurate 1-indexed line numbers', () => {
        const content = [
          'Line 1',
          'Line 2',
          '# Workflow Instruction',
          'Line 4',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches).to.have.lengthOf(1)
        expect(result.reliableMatches[0].startLine).to.equal(3) // 1-indexed
        expect(result.reliableMatches[0].endLine).to.equal(6) // 1-indexed
      })

      it('should handle section at the very start of file', () => {
        const content = [
          '# Workflow Instruction',
          'Content',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches[0].startLine).to.equal(1)
      })

      it('should handle section at the very end of file', () => {
        const content = [
          'User content',
          'User content',
          'User content',
          '# Workflow Instruction',
          'Content',
          '---',
          'Generated by ByteRover CLI for Github Copilot',
        ].join('\n')

        const result = detector.detectLegacyRules(content, 'Github Copilot')

        expect(result.reliableMatches[0].startLine).to.equal(4)
        expect(result.reliableMatches[0].endLine).to.equal(7)
      })
    })
  })
})
