import {randomUUID} from 'node:crypto'
import {existsSync} from 'node:fs'
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises'
import {dirname, join, relative} from 'node:path'

import {BRV_DIR, CONTEXT_TREE_DIR} from '../../server/constants.js'
import {buildCorrectionPrompt, buildGeneratePrompt} from '../../server/core/domain/render/curate-prompt-builder.js'
import {type HtmlWriteError, writeHtmlTopic} from '../../server/infra/render/writer/html-writer.js'

/**
 * Curate session protocol — CLI-side orchestrator for the multi-step
 * curate flow that byterover-tool-mode introduces.
 *
 * Background. Today's `brv curate` runs an LLM agent inside byterover.
 * Tool mode removes that agent: the calling agent (Claude Code) owns
 * the LLM, byterover validates + writes. Because a subprocess can't
 * call back into its parent, the protocol is multi-step: kickoff
 * returns `needs-llm-step` with a prompt; the calling agent produces
 * the response and re-invokes `brv curate` with `--session`/`--response`.
 * Byterover holds session state between invocations.
 *
 * State machine (TKT 02). The orchestrator drives:
 *
 *   kickoff(text)
 *     → state = pending-generate, attempts = 0
 *     → emit needs-llm-step, step = generate-html
 *
 *   continue(response) on pending-generate
 *     → validate + write
 *       on success → emit done, clear session
 *       on failure → state = pending-correct, emit needs-llm-step / correct-html
 *
 *   continue(response) on pending-correct
 *     → validate + write
 *       on success → emit done, clear session
 *       on failure → attempts++; if attempts >= MAX_ATTEMPTS → emit failed,
 *                    else stay in pending-correct, emit correct-html
 *
 * `MAX_ATTEMPTS = 4` (one initial generate + three corrections). After
 * the fourth invalid response the orchestrator terminates the session
 * with `status: failed`.
 *
 * Storage. CLI-local state on disk under `<projectRoot>/.brv/sessions/
 * curate-<id>/state.json`. M3 cleanup may move into daemon task-session
 * sandbox vars once tool mode dispatches through the daemon.
 *
 * Deliberately deferred:
 *   - Search-first UPDATE detection — kickoff today emits a generic
 *     generate-html prompt; UPDATE vs CREATE is the calling agent's
 *     responsibility for now. Wiring `SearchKnowledgeService` requires
 *     daemon-RPC integration, deferred to a follow-up.
 *   - 1h session TTL — abandoned sessions accumulate on disk; M3 prunes
 *     when state moves into the daemon's task-session lifecycle.
 *   - Real prompts — `buildGeneratePrompt` and `buildCorrectionPrompt`
 *     are stubs; TKT 03 ships the production prompt builders with the
 *     condensed bv-* schema and ELEMENT_REGISTRY-derived guidance.
 */

export const CURATE_SESSIONS_DIR = 'sessions'
export const CURATE_SESSION_PREFIX = 'curate-'

/** Maximum number of LLM responses we'll validate before terminating with `failed`. */
const MAX_ATTEMPTS = 4

/**
 * Session ids are uuids generated by `randomUUID()` in `kickoffSession`.
 * Validating that any incoming `--session` argument matches this shape
 * before joining it into a filesystem path closes a path-traversal hole:
 * without this check, a hostile `--session "../../etc"` would let
 * `clearSessionState` rm a directory outside `.brv/sessions/`.
 */
const SESSION_ID_RE = /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i

/**
 * Wire envelope returned by both kickoff and continuation calls.
 * Stable. Reviewer note in the task file: renaming a key here is a
 * breaking change once SKILL.md (TKT 04) ships against this shape.
 */
/** Flat error shape carried in the envelope's `errors` array. */
export type CurateSessionError = {
  attribute?: string
  kind: string
  message: string
  tag?: string
}

export type CurateSessionEnvelope = {
  /** Validation errors. Present on `correct-html` steps and on terminal `failed`. */
  errors?: CurateSessionError[]
  /**
   * Path to the written topic file. Relative to `<projectRoot>/.brv/context-tree/`
   * (e.g. `security/auth.html`). Present when `status === 'done'`.
   */
  filePath?: string
  /** Aggregated success flag — `true` when the overall protocol made progress (not the LLM-step result). */
  ok: boolean
  /** Free-text instruction for the calling agent's LLM. TKT 03 replaces the stubs with the real prompts. */
  prompt?: string
  /** Optional per-step schema slice (e.g. bv-* spec subset). TKT 03 populates. */
  schema?: object
  /**
   * Session identifier for subsequent continuations. Present on every
   * `needs-llm-step` envelope AND on transient `failed` envelopes
   * (e.g. `kind: empty-response`) where the session remains live and
   * the caller is expected to retry. Absent on terminal failures
   * (`kind: unknown-session`, `missing-content`, `missing-response`,
   * `retry-cap-exceeded`) and on `done`.
   */
  sessionId?: string
  status: 'done' | 'failed' | 'needs-llm-step'
  /** Tells the calling agent what kind of completion to produce. */
  step?: 'correct-html' | 'generate-html'
}

/**
 * On-disk session record. The state machine reads and writes this on
 * every continuation. Type-guarded on read so a corrupted file is
 * treated as "no session" instead of propagating malformed fields.
 */
type CurateSessionState = {
  /**
   * Count of LLM responses we've validated so far against this session.
   * Increments on every continuation. When this reaches `MAX_ATTEMPTS`
   * after another invalid response, the orchestrator terminates with
   * `status: failed` and clears the session.
   */
  attempts: number
  createdAt: number
  /**
   * Most recent invalid HTML response. Carried so the next
   * correct-html prompt can show the calling agent what it just
   * produced (correction works better with concrete previous context
   * than starting from scratch). Empty when the session has only
   * emitted a generate-html step so far.
   */
  lastResponse: string
  /** Which step the orchestrator most recently emitted. */
  step: 'awaiting-correct' | 'awaiting-generate'
  /** The user's original `brv curate "<text>"` argument. */
  userIntent: string
}

type KickoffOptions = {
  content: string
  projectRoot: string
}

type ContinueOptions = {
  projectRoot: string
  response: string
  sessionId: string
}

/**
 * Kickoff a new session. Persists state and returns the
 * `needs-llm-step` / generate-html envelope. No validation runs here —
 * kickoff is just "register the user intent and ask the calling agent
 * to author HTML".
 */
export async function kickoffSession(options: KickoffOptions): Promise<CurateSessionEnvelope> {
  const {content, projectRoot} = options
  const sessionId = randomUUID()

  const state: CurateSessionState = {
    attempts: 0,
    createdAt: Date.now(),
    lastResponse: '',
    step: 'awaiting-generate',
    userIntent: content,
  }

  await writeSessionState(projectRoot, sessionId, state)

  return {
    ok: true,
    prompt: buildGeneratePrompt({userIntent: content}),
    sessionId,
    status: 'needs-llm-step',
    step: 'generate-html',
  }
}

/**
 * Continue an existing session. Validates the response, writes the
 * topic file on success, advances the retry loop on failure, terminates
 * with `failed` once the retry cap is exhausted.
 */
export async function continueSession(options: ContinueOptions): Promise<CurateSessionEnvelope> {
  const {projectRoot, response, sessionId} = options

  // Reject non-uuid session ids before any path join — see SESSION_ID_RE
  // for the threat model. Same `kind` as "session not found" because
  // both end at the same caller-facing outcome (resume failed) and
  // distinguishing the two would leak that we're path-traversal-checking.
  if (!SESSION_ID_RE.test(sessionId)) {
    return unknownSessionEnvelope(sessionId, 'invalid-format')
  }

  const state = await readSessionState(projectRoot, sessionId)
  if (!state) return unknownSessionEnvelope(sessionId, 'not-found')

  // Empty-response is a transient continuation error: the session
  // remains live so the caller can retry without losing context.
  if (response.trim().length === 0) {
    return {
      errors: [{kind: 'empty-response', message: 'Continuation --response must be non-empty.'}],
      ok: false,
      sessionId,
      status: 'failed',
    }
  }

  // Run the writer end-to-end: parse, validate against the registry,
  // and atomically write to `.brv/context-tree/<topic.path>.html`. On
  // validation failure no file lands on disk.
  const contextTreeRoot = join(projectRoot, BRV_DIR, CONTEXT_TREE_DIR)
  const writeResult = await writeHtmlTopic({contextTreeRoot, rawHtml: response})

  state.attempts += 1
  state.lastResponse = response

  if (writeResult.ok) {
    await clearSessionState(projectRoot, sessionId)
    return {
      filePath: relative(contextTreeRoot, writeResult.filePath),
      ok: true,
      status: 'done',
    }
  }

  // Validation failed. Retry cap reached → terminate the session.
  if (state.attempts >= MAX_ATTEMPTS) {
    await clearSessionState(projectRoot, sessionId)
    return {
      errors: [
        {
          kind: 'retry-cap-exceeded',
          message: `Curate session exceeded ${MAX_ATTEMPTS - 1} corrections without producing valid HTML.`,
        },
        ...writeResult.errors.map((e) => mapWriterError(e)),
      ],
      ok: false,
      status: 'failed',
    }
  }

  // Otherwise, keep the session live and ask for a correction.
  state.step = 'awaiting-correct'
  await writeSessionState(projectRoot, sessionId, state)

  return {
    errors: writeResult.errors.map((e) => mapWriterError(e)),
    ok: false,
    prompt: buildCorrectionPrompt({
      errors: writeResult.errors,
      previousHtml: response,
      userIntent: state.userIntent,
    }),
    sessionId,
    status: 'needs-llm-step',
    step: 'correct-html',
  }
}

function unknownSessionEnvelope(sessionId: string, reason: 'invalid-format' | 'not-found'): CurateSessionEnvelope {
  const message =
    reason === 'invalid-format'
      ? `Invalid session id format: ${sessionId}. Expected a uuid returned by a prior kickoff.`
      : `No active session with id ${sessionId}. Either the kickoff was never run, or the session was already completed/cleaned up.`

  return {
    errors: [{kind: 'unknown-session', message}],
    ok: false,
    status: 'failed',
  }
}

/**
 * Convert an `html-writer` error to the protocol's envelope error
 * shape. The writer's shape is richer (per-element `field`/`tag`
 * disambiguation); the envelope intentionally flattens to
 * `{kind, tag?, attribute?, message}` so the calling agent can switch
 * on `kind` without learning the writer's internal taxonomy.
 */
function mapWriterError(err: HtmlWriteError): CurateSessionError {
  switch (err.kind) {
    case 'attribute-validation': {
      return {attribute: err.field, kind: 'attribute-validation', message: err.message, tag: err.tag}
    }

    case 'unknown-bv-element': {
      return {kind: 'unknown-element', message: err.message, tag: err.tag}
    }

    default: {
      // missing-bv-topic, missing-path-attribute, multiple-bv-topic, unsafe-path
      return {kind: err.kind, message: err.message}
    }
  }
}

async function writeSessionState(projectRoot: string, sessionId: string, state: CurateSessionState): Promise<void> {
  const dir = sessionDir(projectRoot, sessionId)
  await mkdir(dir, {recursive: true})
  await writeFile(join(dir, 'state.json'), JSON.stringify(state, null, 2), 'utf8')
}

async function readSessionState(projectRoot: string, sessionId: string): Promise<CurateSessionState | undefined> {
  const file = join(sessionDir(projectRoot, sessionId), 'state.json')
  try {
    const raw = await readFile(file, 'utf8')
    const parsed: unknown = JSON.parse(raw)
    return isCurateSessionState(parsed) ? parsed : undefined
  } catch {
    return undefined
  }
}

/**
 * Type guard for on-disk session state. Catches corrupted writes,
 * manual edits, and schema skew — a mismatched state.json is treated
 * as "no session" rather than proceeding with garbage fields.
 */
function isCurateSessionState(value: unknown): value is CurateSessionState {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  return (
    typeof record.attempts === 'number'
    && typeof record.createdAt === 'number'
    && typeof record.lastResponse === 'string'
    && (record.step === 'awaiting-generate' || record.step === 'awaiting-correct')
    && typeof record.userIntent === 'string'
  )
}

async function clearSessionState(projectRoot: string, sessionId: string): Promise<void> {
  await rm(sessionDir(projectRoot, sessionId), {force: true, recursive: true})
}

function sessionDir(projectRoot: string, sessionId: string): string {
  return join(projectRoot, BRV_DIR, CURATE_SESSIONS_DIR, `${CURATE_SESSION_PREFIX}${sessionId}`)
}

/**
 * Walk up from `start` (default cwd) to the nearest ancestor that
 * contains a `.brv/` marker. Falls back to `start` when no marker is
 * found upward — kickoff from a fresh project (no `.brv/` yet) will
 * create one alongside the cwd, same as today's curate behavior.
 *
 * Returning the canonical project root means a kickoff from the
 * project root and a continuation from a subdirectory land in the
 * same `.brv/sessions/` tree — without this, the second call would
 * silently fail with `unknown-session`.
 */
export function resolveProjectRoot(start: string = process.cwd()): string {
  let current = start
  while (true) {
    if (existsSync(join(current, BRV_DIR))) return current
    const parent = dirname(current)
    if (parent === current) return start // hit fs root, fall back to cwd
    current = parent
  }
}
