import {randomUUID} from 'node:crypto'
import {existsSync} from 'node:fs'
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises'
import {dirname, join} from 'node:path'

import {BRV_DIR} from '../../server/constants.js'

/**
 * Curate session protocol — CLI-side placeholder for the multi-step
 * curate flow that byterover-tool-mode introduces.
 *
 * Background. Today's `brv curate` runs an LLM agent inside byterover.
 * Tool mode removes that agent: the calling agent (Claude Code) owns
 * the LLM, byterover validates + writes. Because a subprocess can't
 * call back into its parent, the protocol is multi-step: kickoff
 * returns `needs-llm-step` with a prompt; the calling agent produces
 * the response and re-invokes `brv curate` with `--session`/`--response`.
 * Byterover holds session state between invocations.
 *
 * Scope of this module (TKT 01). The placeholder always emits one
 * `needs-llm-step` on kickoff and `done` on the first continuation —
 * no real orchestration, no search, no validation. The point is to
 * lock the wire protocol so TKT 02's real state machine and TKT 04's
 * SKILL.md can be written against a stable envelope.
 *
 * Storage. CLI-local state on disk under `<projectRoot>/.brv/sessions/
 * curate-<id>/state.json`. TKT 02 will move state into the daemon's
 * existing task-session sandbox vars when the real orchestrator lands
 * (the search service + index already live in the daemon, so the move
 * collapses two state-stores into one).
 */

export const CURATE_SESSIONS_DIR = 'sessions'
export const CURATE_SESSION_PREFIX = 'curate-'

/**
 * Session ids are uuids generated by `randomUUID()` in `kickoffSession`.
 * Validating that any incoming `--session` argument matches this shape
 * before joining it into a filesystem path closes a path-traversal hole:
 * without this check, a hostile `--session "../../etc"` would let
 * `clearSessionState` rm a directory outside `.brv/sessions/`.
 */
const SESSION_ID_RE = /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i

/**
 * Wire envelope returned by both kickoff and continuation calls.
 * Stable. Reviewer note in the task file: renaming a key here is a
 * breaking change once SKILL.md (TKT 04) ships against this shape.
 */
export type CurateSessionEnvelope = {
  /** Validation errors. Present on `correct-html` steps and on `failed`. */
  errors?: Array<{
    attribute?: string
    kind: string
    message: string
    tag?: string
  }>
  /** Set when `status === 'done'` — relative path under `.brv/context-tree/`. */
  filePath?: string
  /** Aggregated success flag — `true` when the overall protocol made progress (not the LLM-step result). */
  ok: boolean
  /** Free-text instruction for the calling agent's LLM. Placeholder emits a stub string. */
  prompt?: string
  /** Optional per-step schema slice (e.g. bv-* spec subset). Placeholder omits. */
  schema?: object
  /**
   * Session identifier for subsequent continuations. Present on every
   * `needs-llm-step` envelope AND on transient `failed` envelopes
   * (e.g. `kind: empty-response`) where the session remains live and
   * the caller is expected to retry. Absent on terminal failures
   * (`kind: unknown-session`, `missing-content`, `missing-response`)
   * and on `done`.
   */
  sessionId?: string
  status: 'done' | 'failed' | 'needs-llm-step'
  /** Tells the calling agent what kind of completion to produce. */
  step?: 'correct-html' | 'generate-html'
}

/**
 * On-disk session record. Schema is intentionally minimal for the
 * placeholder — TKT 02's real orchestrator will extend with state
 * enum, retry counter, user intent, etc.
 */
type CurateSessionState = {
  createdAt: number
  /** Session step the placeholder last emitted; trivial state machine. */
  step: 'awaiting-generate'
  userIntent: string
}

type KickoffOptions = {
  content: string
  projectRoot: string
}

type ContinueOptions = {
  projectRoot: string
  response: string
  sessionId: string
}

/**
 * Kickoff a new placeholder session. Persists state and returns the
 * `needs-llm-step` envelope. Always succeeds (no validation in the
 * placeholder).
 */
export async function kickoffSession(options: KickoffOptions): Promise<CurateSessionEnvelope> {
  const {content, projectRoot} = options
  const sessionId = randomUUID()

  const state: CurateSessionState = {
    createdAt: Date.now(),
    step: 'awaiting-generate',
    userIntent: content,
  }

  await writeSessionState(projectRoot, sessionId, state)

  return {
    ok: true,
    prompt: buildStubGeneratePrompt(content),
    sessionId,
    status: 'needs-llm-step',
    step: 'generate-html',
  }
}

/**
 * Continue an existing session. Reads state, marks the session
 * complete, removes state. The placeholder always succeeds on first
 * continuation; TKT 02 wires real validation and the correct-html
 * retry loop.
 */
export async function continueSession(options: ContinueOptions): Promise<CurateSessionEnvelope> {
  const {projectRoot, response, sessionId} = options

  // Reject non-uuid session ids before any path join — see SESSION_ID_RE
  // for the threat model. Same `kind` as "session not found" because
  // both end at the same caller-facing outcome (resume failed) and
  // distinguishing the two would leak that we're path-traversal-checking.
  if (!SESSION_ID_RE.test(sessionId)) {
    return {
      errors: [
        {
          kind: 'unknown-session',
          message: `Invalid session id format: ${sessionId}. Expected a uuid returned by a prior kickoff.`,
        },
      ],
      ok: false,
      status: 'failed',
    }
  }

  const state = await readSessionState(projectRoot, sessionId)
  if (!state) {
    return {
      errors: [
        {
          kind: 'unknown-session',
          message: `No active session with id ${sessionId}. Either the kickoff was never run, or the session was already completed/cleaned up.`,
        },
      ],
      ok: false,
      status: 'failed',
    }
  }

  // Placeholder: validate response is non-empty as a sanity check;
  // TKT 02 replaces this with the real validateHtmlTopic + correction
  // retry loop.
  if (!response || response.trim().length === 0) {
    return {
      errors: [
        {
          kind: 'empty-response',
          message: 'Continuation --response must be non-empty.',
        },
      ],
      ok: false,
      sessionId,
      status: 'failed',
    }
  }

  await clearSessionState(projectRoot, sessionId)

  return {
    filePath: `placeholder/${sessionId}.html`,
    ok: true,
    status: 'done',
  }
}

function buildStubGeneratePrompt(userIntent: string): string {
  return [
    `Generate a <bv-topic>...</bv-topic> HTML document for the following user intent:`,
    '',
    userIntent,
    '',
    `[PLACEHOLDER PROMPT — TKT 03 replaces this with the full schema + UPDATE-vs-CREATE framing.]`,
    `Return ONLY the bv-topic document. No prose, no code fences.`,
  ].join('\n')
}

async function writeSessionState(projectRoot: string, sessionId: string, state: CurateSessionState): Promise<void> {
  const dir = sessionDir(projectRoot, sessionId)
  await mkdir(dir, {recursive: true})
  await writeFile(join(dir, 'state.json'), JSON.stringify(state, null, 2), 'utf8')
}

async function readSessionState(projectRoot: string, sessionId: string): Promise<CurateSessionState | undefined> {
  const file = join(sessionDir(projectRoot, sessionId), 'state.json')
  try {
    const raw = await readFile(file, 'utf8')
    const parsed: unknown = JSON.parse(raw)
    return isCurateSessionState(parsed) ? parsed : undefined
  } catch {
    return undefined
  }
}

/**
 * Type guard for on-disk session state. Catches corrupted writes,
 * manual edits, and schema skew when TKT 02 extends the shape — a
 * mismatched state.json is treated as "no session" rather than
 * proceeding with garbage fields.
 */
function isCurateSessionState(value: unknown): value is CurateSessionState {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  return (
    typeof record.createdAt === 'number'
    && record.step === 'awaiting-generate'
    && typeof record.userIntent === 'string'
  )
}

async function clearSessionState(projectRoot: string, sessionId: string): Promise<void> {
  await rm(sessionDir(projectRoot, sessionId), {force: true, recursive: true})
}

function sessionDir(projectRoot: string, sessionId: string): string {
  return join(projectRoot, BRV_DIR, CURATE_SESSIONS_DIR, `${CURATE_SESSION_PREFIX}${sessionId}`)
}

/**
 * Walk up from `start` (default cwd) to the nearest ancestor that
 * contains a `.brv/` marker. Falls back to `start` when no marker is
 * found upward — kickoff from a fresh project (no `.brv/` yet) will
 * create one alongside the cwd, same as today's curate behavior.
 *
 * Returning the canonical project root means a kickoff from the
 * project root and a continuation from a subdirectory land in the
 * same `.brv/sessions/` tree — without this, the second call would
 * silently fail with `unknown-session`.
 *
 * TKT 02 will replace this with the canonical `resolveProject()`
 * resolver from `server/infra/project/` once tool mode moves into
 * the daemon (which already uses that resolver).
 */
export function resolveProjectRoot(start: string = process.cwd()): string {
  let current = start
  while (true) {
    if (existsSync(join(current, BRV_DIR))) return current
    const parent = dirname(current)
    if (parent === current) return start // hit fs root, fall back to cwd
    current = parent
  }
}
