import {randomUUID} from 'node:crypto'
import {existsSync} from 'node:fs'
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises'
import {dirname, join, relative, sep} from 'node:path'
import {z} from 'zod'

import type {CurateMeta} from '../../shared/curate-meta.js'

import {ConsoleLogger} from '../../agent/infra/logger/console-logger.js'
import {FileKeyStorage} from '../../agent/infra/storage/file-key-storage.js'
import {BRV_DIR, CONTEXT_TREE_DIR} from '../../server/constants.js'
import {buildCorrectionPrompt, buildGeneratePrompt} from '../../server/core/domain/render/curate-prompt-builder.js'
import {ProjectConfigStore} from '../../server/infra/config/file-config-store.js'
import {RuntimeSignalStore} from '../../server/infra/context-tree/runtime-signal-store.js'
import {bumpSidecarOnCurateWrite} from '../../server/infra/context-tree/tool-mode-sidecar-updaters.js'
import {backupContextTreeFile, buildCurateHtmlLogEntry} from '../../server/infra/process/curate-html-log.js'
import {type HtmlWriteError, validateHtmlTopic, writeHtmlTopic} from '../../server/infra/render/writer/html-writer.js'
import {FileCurateLogStore} from '../../server/infra/storage/file-curate-log-store.js'
import {FileReviewBackupStore} from '../../server/infra/storage/file-review-backup-store.js'
import {getProjectDataDir} from '../../server/utils/path-utils.js'
import {CurateMetaSchema} from '../../shared/curate-meta.js'

/**
 * Curate session protocol — CLI-side orchestrator for the multi-step
 * curate flow that byterover-tool-mode introduces.
 *
 * Background. Today's `brv curate` runs an LLM agent inside byterover.
 * Tool mode removes that agent: the calling agent (Claude Code) owns
 * the LLM, byterover validates + writes. Because a subprocess can't
 * call back into its parent, the protocol is multi-step: kickoff
 * returns `needs-llm-step` with a prompt; the calling agent produces
 * the response and re-invokes `brv curate` with `--session`/`--response`.
 * Byterover holds session state between invocations.
 *
 * State machine (TKT 02). The orchestrator drives:
 *
 *   kickoff(text)
 *     → state = pending-generate, attempts = 0
 *     → emit needs-llm-step, step = generate-html
 *
 *   continue(response) on pending-generate
 *     → validate + write
 *       on success → emit done, clear session
 *       on failure → state = pending-correct, emit needs-llm-step / correct-html
 *
 *   continue(response) on pending-correct
 *     → validate + write
 *       on success → emit done, clear session
 *       on failure → attempts++; if attempts >= MAX_ATTEMPTS → emit failed,
 *                    else stay in pending-correct, emit correct-html
 *
 * `MAX_ATTEMPTS = 4` (one initial generate + three corrections). After
 * the fourth invalid response the orchestrator terminates the session
 * with `status: failed`.
 *
 * Storage. CLI-local state on disk under `<projectRoot>/.brv/sessions/
 * curate-<id>/state.json`. M3 cleanup may move into daemon task-session
 * sandbox vars once tool mode dispatches through the daemon.
 *
 * Deliberately deferred:
 *   - Search-first UPDATE detection — kickoff today emits a generic
 *     generate-html prompt; UPDATE vs CREATE is the calling agent's
 *     responsibility for now. Wiring `SearchKnowledgeService` requires
 *     daemon-RPC integration, deferred to a follow-up.
 *   - 1h session TTL — abandoned sessions accumulate on disk; M3 prunes
 *     when state moves into the daemon's task-session lifecycle.
 *   - Real prompts — `buildGeneratePrompt` and `buildCorrectionPrompt`
 *     are stubs; TKT 03 ships the production prompt builders with the
 *     condensed bv-* schema and ELEMENT_REGISTRY-derived guidance.
 */

export const CURATE_SESSIONS_DIR = 'sessions'
export const CURATE_SESSION_PREFIX = 'curate-'

/** Maximum number of LLM responses we'll validate before terminating with `failed`. */
const MAX_ATTEMPTS = 4

/**
 * Session ids are uuids generated by `randomUUID()` in `kickoffSession`.
 * Validating that any incoming `--session` argument matches this shape
 * before joining it into a filesystem path closes a path-traversal hole:
 * without this check, a hostile `--session "../../etc"` would let
 * `clearSessionState` rm a directory outside `.brv/sessions/`.
 */
const SESSION_ID_RE = /^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i

/**
 * Wire envelope returned by both kickoff and continuation calls.
 * Stable. Reviewer note in the task file: renaming a key here is a
 * breaking change once SKILL.md (TKT 04) ships against this shape.
 */
/** Flat error shape carried in the envelope's `errors` array. */
export type CurateSessionError = {
  attribute?: string
  /**
   * Present on `kind: 'path-exists'` when the prior file was readable.
   * Carries the existing file's full bytes so the calling agent can
   * merge new content into the existing topic instead of silently
   * clobbering it. Mirrors what is embedded inline into the correction
   * prompt. Absent (`undefined`) when the file exists but its content
   * could not be read — consumers MUST treat that as "prior content
   * unavailable", NOT as "topic is empty".
   */
  existingContent?: string
  kind: string
  message: string
  tag?: string
}

export type CurateSessionEnvelope = {
  /** Validation errors. Present on `correct-html` steps and on terminal `failed`. */
  errors?: CurateSessionError[]
  /**
   * Path to the written topic file. Relative to `<projectRoot>/.brv/context-tree/`
   * (e.g. `security/auth.html`). Present when `status === 'done'`.
   */
  filePath?: string
  /** Aggregated success flag — `true` when the overall protocol made progress (not the LLM-step result). */
  ok: boolean
  /** Free-text instruction for the calling agent's LLM. TKT 03 replaces the stubs with the real prompts. */
  prompt?: string
  /** Optional per-step schema slice (e.g. bv-* spec subset). TKT 03 populates. */
  schema?: object
  /**
   * Session identifier for subsequent continuations. Present on every
   * `needs-llm-step` envelope AND on transient `failed` envelopes
   * (e.g. `kind: empty-response`) where the session remains live and
   * the caller is expected to retry. Absent on terminal failures
   * (`kind: unknown-session`, `missing-content`, `missing-response`,
   * `retry-cap-exceeded`) and on `done`.
   */
  sessionId?: string
  status: 'done' | 'failed' | 'needs-llm-step'
  /** Tells the calling agent what kind of completion to produce. */
  step?: 'correct-html' | 'generate-html'
}

/**
 * On-disk session record. The state machine reads and writes this on
 * every continuation. Type-guarded on read so a corrupted file is
 * treated as "no session" instead of propagating malformed fields.
 */
type CurateSessionState = {
  /**
   * Count of LLM responses we've validated so far against this session.
   * Increments on every continuation. When this reaches `MAX_ATTEMPTS`
   * after another invalid response, the orchestrator terminates with
   * `status: failed` and clears the session.
   */
  attempts: number
  createdAt: number
  /**
   * Most recent invalid HTML response. Carried so the next
   * correct-html prompt can show the calling agent what it just
   * produced (correction works better with concrete previous context
   * than starting from scratch). Empty when the session has only
   * emitted a generate-html step so far.
   */
  lastResponse: string
  /** Which step the orchestrator most recently emitted. */
  step: 'awaiting-correct' | 'awaiting-generate'
  /** The user's original `brv curate "<text>"` argument. */
  userIntent: string
}

type KickoffOptions = {
  content: string
  projectRoot: string
}

type ContinueOptions = {
  /**
   * Opt-in to clobber an existing topic at the resolved path. Default
   * `false`: the writer's overwrite guard surfaces `path-exists` as a
   * correctable validation error. Set `true` only when the calling
   * agent has consciously decided to replace prior content (today
   * surfaced via the `--overwrite` flag on `brv curate --session …`).
   */
  confirmOverwrite?: boolean
  projectRoot: string
  response: string
  sessionId: string
}

/**
 * Kickoff a new session. Persists state and returns the
 * `needs-llm-step` / generate-html envelope. No validation runs here —
 * kickoff is just "register the user intent and ask the calling agent
 * to author HTML".
 */
export async function kickoffSession(options: KickoffOptions): Promise<CurateSessionEnvelope> {
  const {content, projectRoot} = options
  const sessionId = randomUUID()

  const state: CurateSessionState = {
    attempts: 0,
    createdAt: Date.now(),
    lastResponse: '',
    step: 'awaiting-generate',
    userIntent: content,
  }

  await writeSessionState(projectRoot, sessionId, state)

  return {
    ok: true,
    prompt: buildGeneratePrompt({userIntent: content}),
    sessionId,
    status: 'needs-llm-step',
    step: 'generate-html',
  }
}

/**
 * Parsed CLI envelope response. Mirrors the MCP tool's typed input but
 * arrives as a JSON string on the `--response` flag, so we have to
 * parse + validate here. `meta` is optional — agents that don't supply
 * it still curate successfully (just no review surfacing for that entry).
 */
const CurateResponseEnvelopeSchema = z.object({
  html: z.string().min(1),
  meta: CurateMetaSchema.optional(),
})

/**
 * Custom error thrown by `parseCurateResponse` when the agent's response
 * is not a well-formed envelope. Carries `kind: 'invalid-response-format'`
 * so the orchestrator can map it to the envelope's structured `errors[]`
 * shape without coupling parsing to envelope construction.
 */
class InvalidResponseFormatError extends Error {
  readonly kind = 'invalid-response-format'
}

/**
 * Parse the agent's `--response` payload as a JSON envelope `{html, meta?}`.
 *
 * The CLI session protocol used to accept raw HTML on `--response`; M4
 * switches to a structured envelope so the calling agent's LLM can
 * supply operation metadata (impact, type, reason) alongside the HTML
 * for the HITL review pipeline.
 *
 * Throws `InvalidResponseFormatError` with `kind: 'invalid-response-format'`
 * on malformed JSON, missing/empty `html`, or invalid `meta`. The caller
 * (continueSession) catches and maps to a structured envelope error so
 * the calling agent sees a clear "your response shape was wrong" signal
 * pointing at the envelope contract.
 */
export function parseCurateResponse(raw: string): {html: string; meta?: CurateMeta} {
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch {
    throw new InvalidResponseFormatError(
      '--response must be a JSON envelope `{"html": "<bv-topic>...</bv-topic>", "meta": {...}}`. Got non-JSON input.',
    )
  }

  const result = CurateResponseEnvelopeSchema.safeParse(parsed)
  if (!result.success) {
    const issue = result.error.issues[0]
    const field = issue?.path.join('.') || '<root>'
    throw new InvalidResponseFormatError(
      `--response envelope failed validation at \`${field}\`: ${issue?.message ?? 'unknown error'}. Expected \`{"html": "<bv-topic>...</bv-topic>", "meta": {...}}\`.`,
    )
  }

  return {html: result.data.html, meta: result.data.meta}
}

/**
 * Continue an existing session. Validates the response, writes the
 * topic file on success, advances the retry loop on failure, terminates
 * with `failed` once the retry cap is exhausted.
 */
export async function continueSession(options: ContinueOptions): Promise<CurateSessionEnvelope> {
  const {confirmOverwrite = false, projectRoot, response, sessionId} = options

  // Reject non-uuid session ids before any path join — see SESSION_ID_RE
  // for the threat model. Same `kind` as "session not found" because
  // both end at the same caller-facing outcome (resume failed) and
  // distinguishing the two would leak that we're path-traversal-checking.
  if (!SESSION_ID_RE.test(sessionId)) {
    return unknownSessionEnvelope(sessionId, 'invalid-format')
  }

  const state = await readSessionState(projectRoot, sessionId)
  if (!state) return unknownSessionEnvelope(sessionId, 'not-found')

  // Empty-response is a transient continuation error: the session
  // remains live so the caller can retry without losing context.
  if (response.trim().length === 0) {
    return {
      errors: [{kind: 'empty-response', message: 'Continuation --response must be non-empty.'}],
      ok: false,
      sessionId,
      status: 'failed',
    }
  }

  // Parse the JSON envelope before touching the writer. A malformed
  // envelope is a protocol-level failure (agent didn't follow the
  // contract) — distinct from HTML validation failure (agent followed
  // the contract but the HTML inside is wrong). The session stays
  // alive so the caller can retry with a corrected envelope.
  let parsed: {html: string; meta?: CurateMeta}
  try {
    parsed = parseCurateResponse(response)
  } catch (error) {
    if (error instanceof InvalidResponseFormatError) {
      return {
        errors: [{kind: error.kind, message: error.message}],
        ok: false,
        sessionId,
        status: 'failed',
      }
    }

    throw error
  }

  const {html, meta} = parsed

  // Run the writer end-to-end: parse, validate against the registry,
  // and atomically write to `.brv/context-tree/<topic.path>.html`. On
  // validation failure no file lands on disk.
  const contextTreeRoot = join(projectRoot, BRV_DIR, CONTEXT_TREE_DIR)

  // Pre-resolve topicPath + existedBefore for the log entry. parse5 is
  // cheap (validateHtmlTopic re-runs internally inside writeHtmlTopic
  // so we don't risk drift). On parse failure topicPath is undefined
  // and the log entry uses the sentinel path.
  const preValidation = validateHtmlTopic(html)
  const topicPath = preValidation.ok ? preValidation.topicPath : undefined
  const absoluteTopicPath = topicPath === undefined ? undefined : join(contextTreeRoot, `${topicPath}.html`)
  const existedBefore = absoluteTopicPath !== undefined && existsSync(absoluteTopicPath)

  // Snapshot the project's reviewDisabled state once for this continuation.
  // Reading it twice (here + in persistCurateLog) could race a mid-task
  // `brv review --enable/--disable` toggle and produce inconsistent semantics
  // between the backup decision and the log-entry decision.
  const reviewDisabled = await resolveProjectReviewDisabled(projectRoot)

  // Seed the review-backup BEFORE the destructive write. Without this, an
  // UPDATE-shaped continuation (confirmOverwrite=true over an existing topic)
  // creates a `reviewStatus: pending` log entry but leaves nothing for
  // `brv review reject` to restore from — review-handler.ts:152 then treats
  // the missing backup as ADD and `unlink`s the file, destroying the user's
  // prior knowledge. backupContextTreeFile honors reviewDisabled and ENOENT
  // gracefully, so it's safe to call on every continuation regardless of
  // whether the file existed.
  if (absoluteTopicPath !== undefined && existedBefore) {
    await backupContextTreeFile({
      absoluteFilePath: absoluteTopicPath,
      contextTreeRoot,
      reviewBackupStore: new FileReviewBackupStore(join(projectRoot, BRV_DIR)),
      reviewDisabled,
    })
  }

  const startedAt = Date.now()
  const writeResult = await writeHtmlTopic({confirmOverwrite, contextTreeRoot, rawHtml: html})
  const completedAt = Date.now()

  // Mirror the curate into the runtime-signal sidecar so prune (and any
  // future signal-driven ranking) has real data. Best-effort: a failure
  // here must never block the write that already succeeded — but emit a
  // warn so an operator hitting a corrupt key store / permission denied
  // on the project data dir has a breadcrumb (a bare catch{} hides it).
  if (writeResult.ok) {
    const sidecarLogger = new ConsoleLogger()
    try {
      const keyStorage = new FileKeyStorage({storageDir: getProjectDataDir(projectRoot)})
      await keyStorage.initialize()
      const runtimeSignalStore = new RuntimeSignalStore(keyStorage, sidecarLogger)
      await bumpSidecarOnCurateWrite({
        existedBefore,
        logger: sidecarLogger,
        // Forward-slash normalize so the sidecar key matches the daemon's
        // curate-html-direct path (`agent-process.ts`) on Windows.
        relPath: relative(contextTreeRoot, writeResult.filePath).replaceAll(sep, '/'),
        store: runtimeSignalStore,
      })
    } catch (error) {
      sidecarLogger.warn(
        `tool-mode-curate: sidecar bump init failed for ${projectRoot}: ${error instanceof Error ? error.message : String(error)}`,
      )
    }
  }

  await persistCurateLog({
    completedAt,
    confirmOverwrite,
    existedBefore,
    // Absolute path — review-handler treats `op.filePath` as absolute and
    // calls `relative(contextTreeDir, ...)` to derive its display key.
    // Mirrors dream-executor's convention.
    filePath: writeResult.ok ? writeResult.filePath : undefined,
    intent: state.userIntent,
    meta,
    projectRoot,
    reviewDisabled,
    startedAt,
    taskId: sessionId,
    topicPath,
    writeResult,
  })

  state.attempts += 1
  state.lastResponse = response

  if (writeResult.ok) {
    await clearSessionState(projectRoot, sessionId)
    return {
      filePath: relative(contextTreeRoot, writeResult.filePath),
      ok: true,
      status: 'done',
    }
  }

  // Validation failed. Retry cap reached → terminate the session.
  if (state.attempts >= MAX_ATTEMPTS) {
    await clearSessionState(projectRoot, sessionId)
    return {
      errors: [
        {
          kind: 'retry-cap-exceeded',
          message: `Curate session exceeded ${MAX_ATTEMPTS - 1} corrections without producing valid HTML.`,
        },
        ...writeResult.errors.map((e) => mapWriterError(e)),
      ],
      ok: false,
      status: 'failed',
    }
  }

  // Otherwise, keep the session live and ask for a correction.
  state.step = 'awaiting-correct'
  await writeSessionState(projectRoot, sessionId, state)

  return {
    errors: writeResult.errors.map((e) => mapWriterError(e)),
    ok: false,
    prompt: buildCorrectionPrompt({
      errors: writeResult.errors,
      previousHtml: response,
      userIntent: state.userIntent,
    }),
    sessionId,
    status: 'needs-llm-step',
    step: 'correct-html',
  }
}

function unknownSessionEnvelope(sessionId: string, reason: 'invalid-format' | 'not-found'): CurateSessionEnvelope {
  const message =
    reason === 'invalid-format'
      ? `Invalid session id format: ${sessionId}. Expected a uuid returned by a prior kickoff.`
      : `No active session with id ${sessionId}. Either the kickoff was never run, or the session was already completed/cleaned up.`

  return {
    errors: [{kind: 'unknown-session', message}],
    ok: false,
    status: 'failed',
  }
}

/**
 * Convert an `html-writer` error to the protocol's envelope error
 * shape. The writer's shape is richer (per-element `field`/`tag`
 * disambiguation); the envelope intentionally flattens to
 * `{kind, tag?, attribute?, message}` so the calling agent can switch
 * on `kind` without learning the writer's internal taxonomy.
 */
function mapWriterError(err: HtmlWriteError): CurateSessionError {
  switch (err.kind) {
    case 'attribute-validation': {
      return {attribute: err.field, kind: 'attribute-validation', message: err.message, tag: err.tag}
    }

    case 'path-exists': {
      // Surface the prior content in a structured field so JSON-driven
      // consumers can merge without re-parsing the prompt; the same
      // content is also inlined into the correction prompt for LLM-
      // driven callers.
      return {existingContent: err.existingContent, kind: 'path-exists', message: err.message}
    }

    case 'unknown-bv-element': {
      return {kind: 'unknown-element', message: err.message, tag: err.tag}
    }

    default: {
      // missing-bv-topic, missing-path-attribute, multiple-bv-topic, unsafe-path
      return {kind: err.kind, message: err.message}
    }
  }
}

/**
 * Build + persist a CurateLogEntry for an in-process CLI continuation.
 *
 * The CLI session runs in-process (no daemon round-trip for the write),
 * so the log entry is written directly here. `FileCurateLogStore` uses
 * atomic tmp+rename writes — safe to interleave with daemon writes from
 * the same project.
 *
 * Logging is best-effort: errors are swallowed (just like daemon-side
 * `curate-log-handler`) so a transient FS error doesn't fail an
 * otherwise-successful curate. The user can still recover via re-run.
 */
async function persistCurateLog(input: {
  completedAt: number
  confirmOverwrite: boolean
  existedBefore: boolean
  filePath?: string
  intent: string
  meta?: CurateMeta
  projectRoot: string
  /**
   * Snapshot of the project's `reviewDisabled` flag at the start of the
   * continuation. Threaded in (rather than re-read here) so the backup
   * decision and the log-entry decision observe the same value even if
   * the user toggles `brv review --enable/--disable` mid-task.
   */
  reviewDisabled: boolean
  startedAt: number
  taskId: string
  topicPath?: string
  writeResult: Awaited<ReturnType<typeof writeHtmlTopic>>
}): Promise<void> {
  try {
    const store = new FileCurateLogStore({baseDir: getProjectDataDir(input.projectRoot)})
    const id = await store.getNextId()
    const entry = buildCurateHtmlLogEntry({
      completedAt: input.completedAt,
      confirmOverwrite: input.confirmOverwrite,
      existedBefore: input.existedBefore,
      filePath: input.filePath,
      id,
      intent: input.intent,
      meta: input.meta,
      reviewDisabled: input.reviewDisabled,
      startedAt: input.startedAt,
      taskId: input.taskId,
      topicPath: input.topicPath,
      writeResult: input.writeResult,
    })
    await store.save(entry)
  } catch (error) {
    // Best-effort: log persistence must never fail the curate. Surface a
    // single-line stderr signal so a user diagnosing "my curate ran but
    // `brv review pending` is empty" has something to grep — paralleling
    // the daemon-side agentLog at `agent-process.ts > curate-html-direct`.
    process.stderr.write(
      `brv curate: failed to persist review log entry: ${error instanceof Error ? error.message : String(error)}\n`,
    )
  }
}

/**
 * Read the project's `reviewDisabled` flag for the CLI's in-process
 * session continuation. Equivalent of the daemon's `resolveReviewDisabled`
 * in `brv-server.ts`. Returns `false` when the config file is absent
 * (fail-open: review enabled by default).
 */
async function resolveProjectReviewDisabled(projectRoot: string): Promise<boolean> {
  try {
    const config = await new ProjectConfigStore().read(projectRoot)
    return config?.reviewDisabled === true
  } catch {
    return false
  }
}

async function writeSessionState(projectRoot: string, sessionId: string, state: CurateSessionState): Promise<void> {
  const dir = sessionDir(projectRoot, sessionId)
  await mkdir(dir, {recursive: true})
  await writeFile(join(dir, 'state.json'), JSON.stringify(state, null, 2), 'utf8')
}

async function readSessionState(projectRoot: string, sessionId: string): Promise<CurateSessionState | undefined> {
  const file = join(sessionDir(projectRoot, sessionId), 'state.json')
  try {
    const raw = await readFile(file, 'utf8')
    const parsed: unknown = JSON.parse(raw)
    return isCurateSessionState(parsed) ? parsed : undefined
  } catch {
    return undefined
  }
}

/**
 * Type guard for on-disk session state. Catches corrupted writes,
 * manual edits, and schema skew — a mismatched state.json is treated
 * as "no session" rather than proceeding with garbage fields.
 */
function isCurateSessionState(value: unknown): value is CurateSessionState {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  return (
    typeof record.attempts === 'number'
    && typeof record.createdAt === 'number'
    && typeof record.lastResponse === 'string'
    && (record.step === 'awaiting-generate' || record.step === 'awaiting-correct')
    && typeof record.userIntent === 'string'
  )
}

async function clearSessionState(projectRoot: string, sessionId: string): Promise<void> {
  await rm(sessionDir(projectRoot, sessionId), {force: true, recursive: true})
}

function sessionDir(projectRoot: string, sessionId: string): string {
  return join(projectRoot, BRV_DIR, CURATE_SESSIONS_DIR, `${CURATE_SESSION_PREFIX}${sessionId}`)
}

/**
 * Walk up from `start` (default cwd) to the nearest ancestor that
 * contains a `.brv/` marker. Falls back to `start` when no marker is
 * found upward — kickoff from a fresh project (no `.brv/` yet) will
 * create one alongside the cwd, same as today's curate behavior.
 *
 * Returning the canonical project root means a kickoff from the
 * project root and a continuation from a subdirectory land in the
 * same `.brv/sessions/` tree — without this, the second call would
 * silently fail with `unknown-session`.
 */
export function resolveProjectRoot(start: string = process.cwd()): string {
  let current = start
  while (true) {
    if (existsSync(join(current, BRV_DIR))) return current
    const parent = dirname(current)
    if (parent === current) return start // hit fs root, fall back to cwd
    current = parent
  }
}
