/**
 * LocalSandbox — UUID variable-naming regression.
 *
 * UUID-shaped task IDs contain hyphens, which are not valid JavaScript
 * identifier characters. When LLM-written code references variables by
 * task ID (`__curate_meta_<taskId>`), it naturally writes underscores —
 * causing a ReferenceError if the sandbox stored the variable using the
 * raw hyphenated form.
 *
 * Originally lived in `test/unit/infra/executor/curate-executor.test.ts`
 * under `describe('CurateExecutor (regression)')`, but post-Phase-1 cutover
 * the executor no longer injects sandbox variables — these tests exercise
 * `LocalSandbox` directly. Moved here so the describe label matches the
 * actual subject under test.
 */

import {expect} from 'chai'

import {LocalSandbox} from '../../../../src/agent/infra/sandbox/local-sandbox.js'

describe('LocalSandbox — UUID variable naming', () => {
  // Typical UUID taskId with hyphens (as generated by crypto.randomUUID())
  const taskId = '8cd8e2d8-a7fc-4371-89ca-59460687c12d'
  // What the LLM would write in code-exec (hyphens → underscores, valid JS identifier)
  const llmGeneratedVarName = '__curate_meta_8cd8e2d8_a7fc_4371_89ca_59460687c12d'

  describe('bug: hyphenated taskId causes variable name mismatch', () => {
    it('should fail with ReferenceError when variable stored with hyphens but accessed with underscores', async () => {
      const sandbox = new LocalSandbox()

      // Old (buggy) behavior: store variable using raw taskId containing hyphens
      const buggyMetaVar = `__curate_meta_${taskId}` // "..._8cd8e2d8-a7fc-..."
      sandbox.updateContext({[buggyMetaVar]: {charCount: 100, lineCount: 5}})

      // LLM writes underscores in code (hyphens are not valid JS identifier chars)
      const result = await sandbox.execute(llmGeneratedVarName)

      // Variable is in sandbox as hyphen-version, but LLM looks up underscore-version → not found
      expect(result.stderr).to.include('ReferenceError')
      expect(result.stderr).to.include(llmGeneratedVarName)
    })
  })

  describe('fix: taskIdSafe with underscores eliminates mismatch', () => {
    it('should succeed when variable stored with underscores matching LLM output', async () => {
      const sandbox = new LocalSandbox()

      // Fixed behavior: replace hyphens before naming sandbox variables
      const taskIdSafe = taskId.replaceAll('-', '_')
      const fixedMetaVar = `__curate_meta_${taskIdSafe}` // all underscores
      sandbox.updateContext({[fixedMetaVar]: {charCount: 100, lineCount: 5}})

      // LLM writes underscores → now matches sandbox variable
      const result = await sandbox.execute(`${llmGeneratedVarName}.charCount`)

      expect(result.stderr).to.equal('')
      expect(result.returnValue).to.equal(100)
    })

    it('should correctly transform all UUID segments (4 hyphens replaced)', () => {
      const taskIdSafe = taskId.replaceAll('-', '_')

      expect(taskIdSafe).to.not.include('-')
      expect(taskIdSafe).to.equal('8cd8e2d8_a7fc_4371_89ca_59460687c12d')

      const metaVar = `__curate_meta_${taskIdSafe}`
      expect(metaVar).to.equal(llmGeneratedVarName)
    })
  })
})
