import {Agent} from '../domain/entities/agent.js'

/**
 * ByteRover CLI generated rule template tag.
 */
export const BR_RULE_TAG = 'Generated by ByteRover CLI for'

/**
 * Interface for rule template service operations.
 */
export interface IRuleTemplateService {
  /**
   * Generates rule content based on the provided agent.
   *
   * @param agent The agent for which to generate the rule content.
   * @returns the generated rule content.
   */
  generateRuleContent: (agent: Agent) => string
}
