import {z} from 'zod'

/**
 * Zod attribute schemas for the index vocabulary.
 *
 * Light validation — the index is system-generated by `IndexGenerator`,
 * so these are a defensive self-check (catch generator bugs) rather than
 * an adversarial-input gate. `passthrough` tolerates unknown attributes,
 * matching the topic-element schema convention.
 *
 * Numeric attributes (`topiccount`, `domaincount`, `count`) are typed as
 * digit strings: HTML attribute values are always strings, so the wire
 * form of `topiccount` is `"6"`, not `6`.
 */

/** A non-negative integer encoded as an HTML attribute string. */
const countString = z
  .string()
  .regex(/^\d+$/, {message: 'must be a non-negative integer'})
  .optional()

/** `<bv-index>` — document root. */
export const BvIndexAttributesSchema = z
  .object({
    domaincount: countString,
    generatedat: z.string().min(1, {message: 'generatedat is required and must be non-empty'}),
    project: z.string().min(1, {message: 'project is required and must be non-empty'}),
    topiccount: countString,
  })
  .passthrough()

/** `<bv-index-domain>` — one section per category/domain. */
export const BvIndexDomainAttributesSchema = z
  .object({
    count: countString,
    name: z.string().min(1, {message: 'name is required and must be non-empty'}),
  })
  .passthrough()

/** `<bv-index-entry>` — one per topic; the routing unit. */
export const BvIndexEntryAttributesSchema = z
  .object({
    format: z.enum(['html', 'markdown']),
    path: z.string().min(1, {message: 'path is required and must be non-empty'}),
    tags: z.string().optional(),
    title: z.string().min(1, {message: 'title is required and must be non-empty'}),
  })
  .passthrough()

/** `<bv-index-description>` — freeform prose block; carries no attributes. */
export const BvIndexDescriptionAttributesSchema = z.object({}).passthrough()
