/**
 * Light validator for the context-tree index document (`index.html`).
 *
 * The index is system-generated by `IndexGenerator`, so this is a
 * defensive self-check — the generator runs it on its own output before
 * the atomic write so a generator bug surfaces loudly rather than
 * producing a malformed `index.html`. It is also the typed contract
 * downstream consumers (the FE index-viewer) build against.
 *
 * Mirrors `validateHtmlTopic`'s shape but for the index vocabulary:
 * requires exactly one `<bv-index>` root, rejects any `bv-*` element
 * outside `INDEX_ELEMENT_REGISTRY`, and runs each element's registered
 * attribute validator.
 */

import type {ElementNode} from '../../../core/domain/render/element-types.js'

import {parseHtml, walkElements} from '../reader/html-parser.js'
import {INDEX_ELEMENT_REGISTRY} from './registry.js'
import {INDEX_ELEMENT_NAMES, type IndexElementName} from './types.js'

export type IndexValidationError =
  | {field: string; kind: 'attribute-validation'; message: string; tag: IndexElementName}
  | {kind: 'missing-bv-index'; message: string}
  | {kind: 'multiple-bv-index'; message: string}
  | {kind: 'unknown-index-element'; message: string; tag: string}

export type IndexValidationResult =
  | {errors: readonly IndexValidationError[]; ok: false}
  | {ok: true}

function isRegisteredIndexElement(tag: string): tag is IndexElementName {
  return (INDEX_ELEMENT_NAMES as readonly string[]).includes(tag)
}

/**
 * Validate an index HTML document. Pure — does not touch disk.
 */
export function validateHtmlIndex(html: string): IndexValidationResult {
  const errors: IndexValidationError[] = []

  const document = parseHtml(html)
  const elements = walkElements(document)
  // `<bv-index>` must be a true document root, not merely present somewhere
  // in the tree — a nested `<bv-index>` inside a `<bv-index-domain>` must
  // not satisfy the guard. `parseHtml` uses `parseFragment`, so document
  // children are the top-level nodes with no `html`/`body` wrapping.
  const roots = document.children.filter(
    (c): c is ElementNode => c.type === 'element' && c.tagName === 'bv-index',
  )

  if (roots.length === 0) {
    return {
      errors: [
        {
          kind: 'missing-bv-index',
          message: 'Index document must contain exactly one <bv-index> root element. Found 0.',
        },
      ],
      ok: false,
    }
  }

  if (roots.length > 1) {
    errors.push({
      kind: 'multiple-bv-index',
      message: `Index document must contain exactly one <bv-index> root. Found ${roots.length}.`,
    })
  }

  for (const el of elements) {
    // Only `bv-*` elements are governed by the index vocabulary. Plain
    // HTML (ul, li, p, …) inside descriptions / entries is left alone.
    if (!el.tagName.startsWith('bv-')) continue

    if (!isRegisteredIndexElement(el.tagName)) {
      errors.push({
        kind: 'unknown-index-element',
        message: `<${el.tagName}> is not part of the index vocabulary. Topic elements and the index vocabulary do not mix.`,
        tag: el.tagName,
      })
      continue
    }

    const result = INDEX_ELEMENT_REGISTRY[el.tagName].validator(el)
    if (!result.valid) {
      for (const e of result.errors) {
        errors.push({field: e.field, kind: 'attribute-validation', message: e.message, tag: el.tagName})
      }
    }
  }

  return errors.length > 0 ? {errors, ok: false} : {ok: true}
}
