/**
 * Live services adapter — wires the abstract `NodeServices` to ByteRover's
 * real infrastructure (LLM via `agent.generate`, write via `executeCurate`).
 *
 * Used by `curate-executor.ts` to back the curate-flow DAG. Tests inject
 * stub services directly and bypass this module.
 *
 * Phase 1 design notes:
 *   - extract: one LLM call per chunk via `agent.generate` (NO agent loop)
 *   - detectConflicts: per-fact subject lookup against the context tree via
 *     the injected `lookupSubject` function. Subjects already present
 *     produce 'update' decisions; others produce 'add'. Phase 2 may add
 *     LLM-driven conflict reasoning.
 *   - write: builds a CurateInput from decisions and calls executeCurate
 *     directly (same path the curate-tool uses today).
 */

import type {NodeServices} from '../../../core/curation/flow/runner.js'
import type {ICipherAgent} from '../../../core/interfaces/i-cipher-agent.js'
import type {ExistingMemoryEntry} from './existing-memory-loader.js'

import {executeCurate} from '../../tools/implementations/curate-tool.js'
import {deriveKeywords, deriveRelatedFromResolved, deriveTags, type ResolvedDecision} from './metadata-derivers.js'

/**
 * Phase 2.5 R-3 (PHASE-2.5-PLAN.md §3.4) — describes where the curate
 * input came from. Threaded into buildReason so the per-leaf `Reason`
 * field carries source provenance for audit-trail.
 */
export interface SourceProvenance {
  /** Human-readable source name (e.g., "cli-text", "package.json", "stdin"). */
  readonly name: string
  /** Source type — file, text (cli paste), stdin. */
  readonly type: 'file' | 'stdin' | 'text'
}

interface BuildLiveServicesDeps {
  readonly agent: ICipherAgent
  readonly basePath?: string
  /**
   * Curate-log identifier (cur-<timestamp>) generated by `CurateLogHandler.onTaskCreate`,
   * forwarded by task-router → agent-process → curate-executor → here.
   * When present, used as the correlation id in `Reason` (preferred over `taskId`).
   * Optional — undefined for direct test invocations that bypass the router.
   */
  readonly logId?: string
  /**
   * Look up existing memory entries for a given subject (e.g., via
   * SearchKnowledgeService). Returns empty array if nothing matches.
   * Failures should be swallowed by the caller — conflict detection is
   * fail-open on missing data (treat unknown as 'add').
   */
  readonly lookupSubject: (subject: string) => Promise<ExistingMemoryEntry[]>
  /** R-3: source provenance threaded into Reason envelope. */
  readonly provenance?: SourceProvenance
  /** R-3: runner taskId, used as fallback correlation id when logId is undefined. */
  readonly taskId?: string
}

const EXTRACTION_PROMPT_PREFIX = `Extract concrete factual statements from the text below. Output ONLY a JSON array of objects matching this schema:
  [
    {"subject": "string (required)", "statement": "string (required)", "category": "convention | environment | other | personal | preference | project | team (optional)"}
  ]
Return an empty array \`[]\` if no clear facts are present. Do NOT wrap the array in any prose, code fence, or commentary.

TEXT:
`

interface ExtractedFact {
  category?: 'convention' | 'environment' | 'other' | 'personal' | 'preference' | 'project' | 'team'
  statement: string
  subject?: string
}

/**
 * Parse a context-tree relative path from the existing-memory loader back
 * into the `(path, title)` shape executeUpdate expects.
 *
 * Input examples (the loader sets `existingId = SearchKnowledgeResult.path`,
 * which is relative to the context tree root):
 *   "project/auth/jwt_tokens.md"           → {path: "project/auth", title: "jwt_tokens"}
 *   "project/auth/oauth/refresh.md"        → {path: "project/auth/oauth", title: "refresh"}
 *   "/project/auth/jwt_tokens.md"          → same as above (leading slash stripped)
 *   "project/auth"                         → undefined (only 2 segments — no title)
 *   "single-segment"                       → undefined
 *
 * Returns undefined when the input cannot be safely interpreted; the caller
 * then falls back to ADD instead of issuing a guaranteed-failure UPDATE.
 */
function parseExistingIdForUpdate(existingId: string): undefined | {path: string; title: string} {
  const cleaned = existingId.replaceAll(/^\/+|\/+$/g, '').replace(/\.md$/, '')
  const parts = cleaned.split('/').filter(Boolean)
  // Need at least domain/topic/title (3) and at most domain/topic/subtopic/title (4).
  if (parts.length < 3 || parts.length > 4) {
    return undefined
  }

  const title = parts.at(-1) ?? ''
  const path = parts.slice(0, -1).join('/')
  if (!title || !path) return undefined
  return {path, title}
}

/**
 * Phase A coarsening (PR578-TOKEN-REGRESSION-FIX-PLAN.md §3.1) — derive a
 * topic from a subject's first underscore-token. Replaces the old per-subject
 * topic derivation that scattered conceptually-related facts into distinct
 * folders (e.g. `auth_login_endpoint`, `auth_token_storage` → 2 folders).
 *
 *   "auth_login_endpoint" → "auth"
 *   "rate_limit_default"  → "rate"
 *   "redis"               → "redis"   (single-token: unchanged)
 *   "_foo"                → "foo"     (filter drops empty leading segment)
 *   ""                    → undefined (caller falls back to 'misc')
 *   undefined             → undefined (caller falls back to 'misc')
 *
 * Why first-token: the LLM extractor consistently uses snake_case subjects
 * where the first segment is the conceptual category. First-token clustering
 * preserves that grouping deterministically, no LLM call required. Subsequent
 * same-prefix curates land in the same folder by construction (same input →
 * same path).
 */
function derivePrefixTopic(subject: string | undefined): string | undefined {
  if (!subject) return undefined
  return subject.split('_').find(Boolean)
}

function parseFactsFromLlmResponse(content: string): ExtractedFact[] {
  // Strip code fences if the LLM wrapped the JSON despite instructions.
  const cleaned = content
    .replace(/^```(?:json)?\n/, '')
    .replace(/\n```$/, '')
    .trim()
  try {
    const parsed = JSON.parse(cleaned) as unknown
    if (!Array.isArray(parsed)) return []
    const out: ExtractedFact[] = []
    for (const item of parsed) {
      if (typeof item !== 'object' || item === null) continue
      const i = item as {category?: unknown; statement?: unknown; subject?: unknown}
      if (typeof i.statement !== 'string' || i.statement.length === 0) continue
      out.push({
        category:
          typeof i.category === 'string' ? (i.category as ExtractedFact['category']) : undefined,
        statement: i.statement,
        subject: typeof i.subject === 'string' ? i.subject : undefined,
      })
    }

    return out
  } catch {
    return []
  }
}

/**
 * Phase 2.5 R-3 (PHASE-2.5-PLAN.md §3.4) — build the per-leaf `Reason`
 * envelope satisfying the Phase 3 UAT-target shape:
 *
 *   Curated from <correlationId> on <ts> via <type>:"<source>";
 *     subject "<subject>" [<category>] inferred from "<statement-preview>".
 *   Decision: <d.reason>   ← appended ONLY when present (UPDATE case)
 *
 * **Critical (review P2)**: the envelope is ALWAYS emitted. UPDATE
 * decisions previously kept their `detectConflicts` placeholder and
 * bypassed provenance entirely, defeating audit-trail. Now `d.reason`
 * is appended INSIDE the envelope as `Decision: <text>`, never replaces it.
 *
 * Correlation id prefers `cur-<logId>` (router-generated, what the UAT
 * cited) over the runner's UUID `taskId`. The taskId fallback exists
 * for direct test invocations that bypass the router.
 *
 * Statement preview (~80 chars) is the closest available proxy for the
 * UAT's "input quote". Phase 4 upgrades this to actual chunk text via
 * a per-decision `chunkIndex` (requires bumping the conflict-decision
 * schema; deferred).
 *
 * Exported so it can be unit-tested in isolation; not test-only.
 */
export function buildReason(
  decision: {readonly action: string; readonly fact: {category?: string; statement: string; subject?: string}; readonly reason?: string},
  taskId: string | undefined,
  logId: string | undefined,
  provenance: SourceProvenance,
): string {
  const correlationId = logId ?? taskId ?? '<unknown-task>'
  const ts = new Date().toISOString()
  const subjectPart = decision.fact.subject ? `"${decision.fact.subject}"` : '<unknown>'
  const categoryPart = decision.fact.category ? `[${decision.fact.category}]` : '[uncategorized]'
  const inputQuote = decision.fact.statement
    .slice(0, 80)
    .replaceAll(/\s+/g, ' ')
    .trim()

  const envelope = `Curated from ${correlationId} on ${ts} via ${provenance.type}:"${provenance.name}"; subject ${subjectPart} ${categoryPart} inferred from "${inputQuote}".`

  return decision.reason ? `${envelope} Decision: ${decision.reason}` : envelope
}

export function buildLiveServices(deps: BuildLiveServicesDeps): NodeServices {
  // R-3: provenance defaults to a no-op shape when caller doesn't supply it
  // (e.g., direct test invocations). buildReason still emits a valid envelope.
  const provenance: SourceProvenance = deps.provenance ?? {name: 'unknown', type: 'text'}
  return {
    async detectConflicts(facts) {
      // Per-fact subject lookup. Cache within the call to avoid repeat
      // searches for facts sharing a subject.
      const lookupCache = new Map<string, ExistingMemoryEntry[]>()
      const decisions = await Promise.all(
        facts.map(async (fact) => {
          if (!fact.subject) {
            return {action: 'add' as const, fact}
          }

          let existingEntries = lookupCache.get(fact.subject)
          if (!existingEntries) {
            try {
              existingEntries = await deps.lookupSubject(fact.subject)
            } catch {
              existingEntries = []
            }

            lookupCache.set(fact.subject, existingEntries)
          }

          if (existingEntries.length === 0) {
            return {action: 'add' as const, fact}
          }

          const matched = existingEntries[0]
          return {
            action: 'update' as const,
            existingId: matched.existingId,
            fact,
            reason: `subject "${fact.subject}" already present at ${matched.existingId ?? 'unknown path'}`,
          }
        }),
      )
      return {decisions}
    },

    async extract(chunk, taskId) {
      const prompt = `${EXTRACTION_PROMPT_PREFIX}${chunk}`
      const response = await deps.agent.generate(prompt, {taskId})
      const facts = parseFactsFromLlmResponse(response.content)
      return {
        facts,
        failed: facts.length === 0 ? 1 : 0,
        succeeded: facts.length === 0 ? 0 : 1,
        total: 1,
      }
    },

    async write(decisions) {
      // executeCurate's parsePath requires `path` to be `domain/topic` or
      // `domain/topic/subtopic` (2-3 segments) — see curate-tool.ts:689.
      // A single segment like "auth" is rejected with "Invalid path format".
      //
      // UPDATE path: honor `existingId` (the path of the matched existing
      // file, supplied by detectConflicts via the existing-memory loader).
      // executeUpdate looks up `${path}/${snake_case(title)}.md`, so we
      // must split existingId back into path + title rather than deriving
      // a fresh title (which would point to a file that doesn't exist).
      //
      // ADD/UPSERT path (Phase A coarsening, PR578 fix plan §3.1):
      //   - domain = fact.category (or 'extracted' for uncategorized facts)
      //   - topic  = derivePrefixTopic(fact.subject) (first underscore-token)
      //              or 'misc' when subject is missing
      //   - title  = topic (so multiple subjects sharing a prefix collide
      //              on the same target file at `${domain}/${topic}/${topic}.md`)
      //
      // Two-pass shape (NEW-1, PHASE-2.6-PLAN §3.2):
      //   Pass 1 resolves each decision's (path, title, type).
      //   Pass 2 (Phase B batching, PR578 §3.1): groups resolved[] by
      //          `${path}/${title}` and emits one operation per bucket
      //          with merged facts/keywords/tags/relations/reasons.
      //          deriveRelatedFromResolved is unioned across the bucket so
      //          cross-links never reference non-materialized files.
      //
      // R-4 / NEW-2 UPSERT consolidation is unchanged in spirit but operates
      // on a coarser key. Same-prefix subjects (e.g. 'auth_login_endpoint',
      // 'auth_token_storage') now share path+title and batch in Pass 2.
      // Cross-prefix subjects stay in distinct folders.

      // Pass 1: resolve target path/title/type for every decision.
      const resolved: Array<ResolvedDecision & {type: 'ADD' | 'UPDATE' | 'UPSERT'}> = decisions.map((d) => {
        const updateTarget = d.action === 'update' && d.existingId
          ? parseExistingIdForUpdate(d.existingId)
          : undefined

        if (updateTarget) {
          return {decision: d, path: updateTarget.path, title: updateTarget.title, type: 'UPDATE'}
        }

        const domain = d.fact.category ?? 'extracted'
        const topic = derivePrefixTopic(d.fact.subject) ?? 'misc'
        return {decision: d, path: `${domain}/${topic}`, title: topic, type: 'UPSERT'}
      })

      // Pass 2 (Phase B): aggregate decisions by (path, title) → one operation
      // per target file with merged `facts`. Phase A's coarsening produces
      // the collisions; Phase B consumes them.
      const targetKey = (r: typeof resolved[number]): string => `${r.path}/${r.title}`

      const byTarget = new Map<string, Array<typeof resolved[number]>>()
      for (const r of resolved) {
        const key = targetKey(r)
        const bucket = byTarget.get(key) ?? []
        bucket.push(r)
        byTarget.set(key, bucket)
      }

      const operations = [...byTarget.values()].map((rs) => {
        // Type resolution: UPDATE wins over UPSERT. A bucket can mix UPDATE
        // (existingId hit, R-1 merge contract) with UPSERT (new path, fresh
        // write). UPDATE must take precedence so executeUpdate's structural-
        // loss merge runs.
        const type: 'ADD' | 'UPDATE' | 'UPSERT' = rs.some((r) => r.type === 'UPDATE') ? 'UPDATE' : rs[0].type
        const primary = rs[0]

        const facts = rs.map((r) => ({
          category: r.decision.fact.category,
          statement: r.decision.fact.statement,
          subject: r.decision.fact.subject,
        }))

        // R-2 (PHASE-2.5-PLAN §3.3): deterministic metadata derivation. No
        // LLM call. Union keywords/tags across the bucket; cap keywords at 8
        // (existing schema limit, see metadata-derivers.ts).
        const keywords = [...new Set(rs.flatMap((r) => deriveKeywords(r.decision.fact)))].slice(0, 8)
        const tags = [...new Set(rs.flatMap((r) => deriveTags(r.decision.fact)))]

        // NEW-1: union relations across all bucket members so cross-link
        // coverage isn't lost. deriveRelatedFromResolved already filters to
        // materialized files, so cross-batch UPDATE merges remain correct.
        const relations = [...new Set(rs.flatMap((r) => deriveRelatedFromResolved(r, resolved)))]

        // R-3 (PHASE-2.5-PLAN §3.4): join per-fact reason envelopes with
        // newlines so each decision's audit-trail context survives. `reason`
        // is written to the markdown body's `## Reason` section
        // (markdown-writer.ts:550-552), NOT to YAML frontmatter — multi-line
        // strings are safe.
        const reason = rs
          .map((r) => buildReason(r.decision, deps.taskId, deps.logId, provenance))
          .join('\n')

        // Summary is a machine-facing preview; truncation mid-statement after
        // join is intentional. Reviewers read `## Reason` for full context.
        const summary = facts
          .map((f) => f.statement)
          .join('; ')
          .slice(0, 200)

        // Phase-6+ enhancement (deferred): if rs.length exceeds ~20, consider
        // splitting back to per-subject buckets to bound executeUpdate's
        // structural-loss work. Empirically buckets are <10 facts; not gating
        // the initial fix.

        return {
          confidence: 'high' as const,
          content: {facts, keywords, relations, tags},
          impact: 'low' as const,
          path: primary.path,
          reason,
          summary,
          title: primary.title,
          type,
        }
      })

      const result = await executeCurate({basePath: deps.basePath, operations})

      return {
        applied: result.applied,
        summary: result.summary,
      }
    },
  }
}
